<body topmargin="40" leftmargin="0" background='../chatroom/bg1.gif' oncontextmenu="self.event.returnValue=false">
<table border="3" cellspacing="0" cellpadding="0" align="center">
<tr>
<td><a href="#" onclick="javascript:parent.actfrm.location.replace('move.asp?direction=tl');"><img name="landtl" src="../image/land/tl.gif" border="0" WIDTH="36" HEIGHT="36"></a></td>
<td><a href="#" onclick="javascript:parent.actfrm.location.replace('move.asp?direction=t');"><img name="landt" src="../image/land/t.gif" border="0" WIDTH="36" HEIGHT="36"></a></td>
<td><a href="#" onclick="javascript:parent.actfrm.location.replace('move.asp?direction=tr');"><img name="landtr" src="../image/land/tr.gif" border="0" WIDTH="36" HEIGHT="36"></a></td>
</tr>
<tr>
<td><a href="#" onclick="javascript:parent.actfrm.location.replace('move.asp?direction=l');"><img name="landl" src="../image/land/l.gif" border="0" WIDTH="36" HEIGHT="36"></a></td>
<td><img name="land" src="../image/land/m.gif" border="0" WIDTH="36" HEIGHT="36"></td>
<td><a href="#" onclick="javascript:parent.actfrm.location.replace('move.asp?direction=r');"><img name="landr" src="../image/land/r.gif" border="0" WIDTH="36" HEIGHT="36"></a></td>
</tr>
<tr>
<td><a href="#" onclick="javascript:parent.actfrm.location.replace('move.asp?direction=bl');"><img name="landbl" src="../image/land/bl.gif" border="0" WIDTH="36" HEIGHT="36"></a></td>
<td><a href="#" onclick="javascript:parent.actfrm.location.replace('move.asp?direction=b');"><img name="landb" src="../image/land/b.gif" border="0" WIDTH="36" HEIGHT="36"></a></td>
<td><a href="#" onclick="javascript:parent.actfrm.location.replace('move.asp?direction=br');"><img name="landbr" src="../image/land/br.gif" border="0" WIDTH="36" HEIGHT="36"></a></td>
</tr>
</table>
</body>