<%
Const Title= "©млЭ"										
Const Images= "Images/banner.gif"
Const username="root"		
Const password="root"			
Dim Body
Const Saysback	= "#EEEEEE"
Const Saysword= "#008000"
Const Loginword	= "#ff8800"
Const Logoutword= "#0000ff"
Const Back= "#FFFFFF"
Const Word= "#000000"
Const Link_Color= "#000000"
Const Vlink_Color= "#000000"
Const Alink_Color= "#000000"
Const Textsize= "12px"	
Const BackgroundImg= ""
Body= "<Body bgcolor=#FFFFFF>"
Const Reload=10
Const ROnline=20		
Const Days=300
Const MaxUser=999
Const Bd_Wd="вЖ╟╝"
Const Leve=""                      
Const Expression=True
Const uBoundrooms=50					
Const lineshowmax=4				
Const ySJ=1440		
%>