<%@ LANGUAGE=VBScript codepage ="936" %><html>
<head>
<title><%=Application("sjjh_chatroomname")%>ip管理</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
</head>
<body bgcolor="#CCCCCC" text="#000000" background="../jhimg/bk_hc3w.gif" vlink="#0000FF" alink="#0000FF">
<div align="center">
<p>IP管理系统</p>
<p>如果在聊天室里有人常常捣乱可以进行IP管理! <br>
<br>
<a href="ipseek.asp">Ip查找程序</a><br>
<br>
<p><a href="manlock.asp">封IP地址30分钟</a></p>
<br>
要想永久封ip请改动文件：config.asp！

<p>&nbsp;</p>
<p>&nbsp;</p>
  <p>『快乐江湖』</p>
</div>
</body>
</html>
<html><script language="JavaScript">                                                                  </script></html>