<%
Response.Expires=0
if Session("yx8_mhjh_username")="" then Response.Redirect "../error.asp?id=016"
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD><TITLE>怡红丽院－女性画廊</TITLE>
<META content="text/html; charset=gb2312" http-equiv=Content-Type><LINK 
href="../../style4.css" rel=stylesheet>
<META content="Microsoft FrontPage 5.0" name=GENERATOR>
</HEAD>
<BODY bgColor=#000000 leftMargin=0 topMargin=0 marginheight="0" marginwidth="0" text="#C0C0C0" background="a15.gif" oncontextmenu=self.event.returnValue=false>
<TABLE border=0 cellPadding=0 cellSpacing=0 width=757>
  <TBODY>
  <TR>
    <TD align=middle vAlign=top width=713>
      <TABLE border=0 cellPadding=0 cellSpacing=0 width="722" height="200">
        <TBODY>
        <TR>
          <TD noWrap width="559" height="49">
            <TABLE border=0 cellPadding=0 cellSpacing=0 width="723">
              <TBODY>
              <TR>
                <TD width="30"></TD>
                <TD width="689">
                  <TABLE border=0 cellPadding=0 cellSpacing=0 height="26" width="728">
                    <TBODY>
                    <TR>
                      <TD rowSpan=3 height="26" width="14"></TD>
                      <TD rowSpan=3 height="26" width="11"></TD>
                      <TD background=../pic/wtdrbg1.gif height="5" width="478">
                      　</TD>
                      <TD rowSpan=3 height="26" width="155">
                        <div align="left">
                          <img border="0" src="tie1.jpg">
                        </div>
                      </TD>
                      <TD rowSpan=3 height="26" width="61" align="right">
                      <div align="left">
                        　
                      </div>
                      <p>　
                      </TD></TR>
                    <TR>
                      <TD align=middle class=redtext height=15 width="478"><font size="2"><font color="#ffffff" size="2"><font color="#696969"><font color="#373737">|</font><font color="#505050">|</font>|</font><font color="#828282">|</font><font color="#9b9b9b">|</font><font color="#b4b4b4">|</font><font color="#cdcdcd">|</font><font color="#e6e6e6">|</font>|</font></font><font color="#ff0000" size="4">魔幻江湖<img height="11" src="a12.gif" width="15">女人画廊</font><font size="2">|<font color="#e6e6e6">|</font><font color="#cdcdcd">|</font><font color="#b4b4b4">|</font><font color="#9b9b9b">|</font><font color="#828282">|</font><font color="#696969">|<font color="#505050">|</font><font color="#373737">|</font></font></font></TD>
                    </TR>
                    <TR>
                      <TD background=../pic/wtdrbg2.gif height="6" width="478">
                      　</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD>
          <TD vAlign=bottom width="138" height="49"></TD></TR>
        <TR>
          <TD width="559" height="15">
          <font color="#ff0000" size="2">● 警告！</font><font color="#ff0000">本站个别内容接近敏感边缘，谢绝不满十八岁人士进入。</font>  
          </TD>        
          <TD width="138" height="15"></TD></TR>        
        <TR>        
          <TD class=bg1         
          style="PADDING-LEFT: 15px; PADDING-RIGHT: 15px" vAlign=top         
            width=559 height="121">         
          <table border="0" cellpadding="0" cellspacing="0" width="746" height="9">        
            <tr>        
                    
                <td align="center" colspan="7" width="734" height="15"> <font size="2" color="read"><b>         
                  <%=session("yx8_mhjh_usercorp")%></b></font><font color="#ff0000">●         
                  注意！</font><font color="#696969">累了一天进去找个小姐三温暖一下，放松一下，可是要看看带够钱了没有哦。这可是有钱人来的地方哦</font>        
                </td>                            
            </tr>                            
            <tr>       
                   
                <td align="center" rowspan="3" width="138" height="1"><img height="5" src="k1.gif" width="130"><br>       
                  <img height="120" src="kb2.gif" width="5"><img height="120" src="w07.jpg" width="120" border="0"><img height="120" src="kb3.gif" width="5"><br>       
                  <img height="5" src="k4.gif" width="130"><img height="5" src="k4.gif" width="130">        
                </td>                            
                   
                <td align="center" rowspan="7" width="166" height="9"><font size="2">屏息的震撼<br>       
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 广褒的轻柔<br>        
                  &nbsp;&nbsp;&nbsp; 诗意的境界</font><br>       
                  <img height="5" src="k1.gif" width="130"><br>       
                  <img height="120" src="kb2.gif" width="5"><img height="120" src="xg008.jpg" width="120" border="0"><img height="120" src="kb3.gif" width="5"><img height="5" src="k4.gif" width="130"><img height="5" src="k4.gif" width="130">&nbsp;&nbsp;&nbsp;&nbsp;        
                  <font size="2">高峰夜留景,深夜昼未明.</font>        
                </td>                            
                   
                <td width="206" rowspan="6" height="9" colspan="2"> <img border="0" src="xg400.jpg">        
                </td>                            
                   
                <td width="179" colspan="2" height="1">        
                  <p align="center"></p>       
                </td>                            
                   
                <td width="37" height="1"> <img border="0" src="yuren1.gif">        
                </td>                            
            </tr>                            
            <tr>       
                   
                <td width="101" height="12" rowspan="5">         
                <p align="center"><img border="0" src="yuren3.gif">        
                </td>                            
                   
                <td width="83" height="1">        
                  <p align="center"> <img border="0" src="yuren2.gif">        
                  </p>       
                </td>                            
                   
                <td width="37" height="1">         
                <img border="0" src="lastpost.gif">         
                </td>                            
            </tr>                            
            <tr>       
                   
                <td width="122" colspan="2" height="1">         
                <p><font color="#FFFFFF">[</font><a href="xiaojie.asp"><font color="#999999">去轻松一下</font></a><font color="#FFFFFF">]</font>         
                </td>                            
                   
            </tr>                            
            <tr>       
                   
                <td width="92" height="9" rowspan="2">         
                <p align="center"><font color="#FFFFFF">[</font><font color="#FFFFFF">        
                </font><a href="dengji.asp"><font color="#999999">应聘上班</font></a><font color="#999999">        
                </font><font color="#FFFFFF">]</font></p>       
                </td>                            
                   
            </tr>                            
            <tr>       
                   
                <td align="center" rowspan="4" width="132" height="1"><br>       
                  <img height="5" src="k1.gif" width="130"><br>       
                  <img height="120" src="kb2.gif" width="5"><img height="120" src="xg005.jpg" width="120" border="0"><img height="120" src="kb3.gif" width="5"><img height="5" src="k4.gif" width="130"><img height="5" src="k4.gif" width="130">        
                </td>                            
                   
            </tr>                            
            <tr>       
                   
                <td width="92" height="1">         
                <font >&nbsp;&nbsp; 血腥的颤抖<br>       
                  火热的扇情<br>       
                  &nbsp;&nbsp;&nbsp;泌润的温和</font>         
                </td>                            
                   
                <td width="37" height="1">         
                <p align="center">            
                </td>                           
            </tr>                           
            <tr>      
                  
                <td width="92" height="1">       
                  <img border="0" src="yuren5.gif"><font><font color="#FFFFFF">[</font><font color="#999999">       
                  </font><a href="javascript:window:close();"><font color="#999999">关闭</font></a><font color="#999999">       
                  </font><font color="#FFFFFF">]</font></font>       
                </td>                           
                  
                <td width="127" height="1"> <font >尽在女性画廊...</font>       
                </td>                           
                  
                <td width="1" height="1"> <img border="0" src="yuren4.gif">       
                </td>                           
            </tr>                           
            <tr>                           
                                       
                <td width="360" valign="middle" align="center" height="17" colspan="3">       
                  小姐上班可以得到50万，赎身需要100万      
                  </td>                               
                                        
                <td width="91" valign="middle" align="center" height="17" colspan="2">        
                  <p align="right"><img border="0" src="yuren6.gif">       
                </td>                              
                                       
            </tr>                              
          </table>                              
          </TD>                                   
          <TD vAlign=top width="138" height="121">           
          </TD></TR>                                   
        </TBODY></TABLE>                                   
    </TD>                                  
  </TR>                                  
  </TBODY></TABLE>                  
<p>　</p>      
</BODY></HTML>