<html>
<head>
<style></style>
<link rel="stylesheet" href="../style.css" type="text/css">
<title>大相国寺</title>
</head>
<body background='../chatroom/bg1.gif' oncontextmenu=self.event.returnValue=false>
<p align=center style='font-size:20;color:yellow'><font color="#000000"><b><br>
  <font color="#000099"><br>
</font>
  欢迎光临大相国寺</b></font> <br>

<table width="56%" border="0" align="center" cellpadding="4" cellspacing="1" bgcolor="#000000">
  <tr bgcolor="#FFFFFF"> 
    <td colspan="3" height="39"> 
      <div align="center"><font size="2" color="#000000">金碧辉煌的相国寺，果然气派不凡，不愧为皇家寺院</font></div>
    </td>
  </tr>
  <tr bgcolor="#FFFFFF"> 
    <td width="27%" height="14"> 
      <div align="center"><font size="2" color="#000000">方式</font></div>
    </td>
    <td width="33%" height="14"> 
      <div align="center"><font size="2" color="#000000">道德</font></div>
    </td>
    <td width="40%" height="14"> 
      <div align="center"><font size="2" color="#000000">花费</font></div>
    </td>
  </tr>
  <tr bgcolor="#FFFFFF"> 
    <td width="27%" height="16"> 
      <div align="center"><font size="2" color="#000000">拜佛</font></div>
    </td>
    <td width="33%" height="16"> 
      <div align="center"><font size="2" color="#000000">40</font></div>
    </td>
    <td width="40%" height="16"> 
      <div align="center"><font color="#000000">2000</font></div>
    </td>
  </tr>
  <tr bgcolor="#FFFFFF"> 
    <td width="27%"> 
      <div align="center"><font size="2" color="#000000">烧香</font></div>
    </td>
    <td width="33%"> 
      <div align="center"><font color="#000000">60</font></div>
    </td>
    <td width="40%"> 
      <div align="center"><font color="#000000">3000</font></div>
    </td>
  </tr>
  <tr bgcolor="#FFFFFF"> 
    <td width="27%"> 
      <div align="center"><font size="2" color="#000000">还愿</font></div>
    </td>
    <td width="33%"> 
      <div align="center"><font color="#000000">80</font></div>
    </td>
    <td width="40%"> 
      <div align="center"><font color="#000000">4000</font></div>
    </td>
  </tr>
  <tr bgcolor="#FFFFFF"> 
    <td width="27%"> 
      <div align="center"><font size="2" color="#000000">捐赠</font></div>
    </td>
    <td width="33%"> 
      <div align="center"><font color="#000000">100</font></div>
    </td>
    <td width="40%"> 
      <div align="center"><font color="#000000">5000</font></div>
    </td>
  </tr>
</table>
<div align="center">
  <center>
<table border=1 bgcolor="#FFFF00" width=350 cellpadding="10" cellspacing="13" style="border-collapse: collapse" bordercolor="#111111">
<tr><td bgcolor=#FFCC66>
<table>
<tr><td>
<form method=POST action='fou2.asp'>
<tr>
          <td align=center>请问，施主来毕寺是想：  
            <select name=jiu size=1> 
              <option value="lao">拜佛 </option> 
              <option value="wu">烧香 </option> 
              <option value="du">还愿 </option> 
              <option value="mao">捐赠 </option> 
            </select> 
</td><td colspan=2 align=center><input type=submit value=确定> 
<tr><td colspan=2 style='font-size:9pt'><hr> 
            佛主说的好：“放下屠刀，立地成佛”，居然施主能来这里，就说明你还有一份仁慈之心！不过香火钱不能少。 <br> 
            </td> 
        </tr> 
</form> 
</table> 
</table> 
    <br> 
  </center> 
</div> 
</body> 
</html>