<html>

<head>
<meta http-equiv="Content-Language" content="zh-cn">
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>恭喜</title>
<LINK href="../style.css" rel=stylesheet>
</head>
<body background='../chatroom/bg1.gif' oncontextmenu=self.event.returnValue=false topMargin="100">
<p align="center">恭喜，你购买礼品成功，谢谢光临！</p>
<p align="center"><a href="lipin.asp"><font color="#0000FF">回礼品店</font></a></p>
</body>
</html>
