<html>
<head>
<title>极地采冰</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<LINK href="../../../style2.css" rel=stylesheet></head>
<body bgcolor="#000000" text="#FFFFFF" topmargin="0" link="#0000FF" vlink="#0000FF" alink="#0000FF" leftmargin="0">
<table width="487" border="1" cellpadding="0" cellspacing="0" align="center">
  <tr> 
    <td height="14" width="39" nowrap> 
      <div align="center"><font size="-1"><a href="maimine.asp" target="cz1">
        <font color="#FF0000">卖出</font></a></font></div>
    </td>
    <td height="14" width="198"><font color="#FFFF00" style="font-size: 9pt">现在一块矿石价钱30000两，选择卖出可以将矿石转换成银两！</font></td>
    <td height="14" width="26" nowrap><font size="-1"><a href="savemine.asp" target="cz1">
    <font color="#FF0000">保存</font></a></font></td>
    <td height="14" width="214"><font color="#FFFF00" style="font-size: 9pt">保存，可以把矿石存放到家里，可以使用练铁，练出好铁卖更好的价钱！</font></td>
  </tr>
</table>
</body>
</html>