<%@ LANGUAGE=VBScript codepage ="936" %><html>
<head>
<title><%=Application("sjjh_chatroomname")%>股票管理</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
</head>
<body bgcolor="#CCCCCC" text="#000000" background="../../jhimg/bk_hc3w.gif" vlink="#0000FF" alink="#0000FF">
<div align="center">
  <p>股票数据管理</p>
  <p>股票数据管理，在这里可以操作股票的所有资料！<br>
    <br>
    <a href="addstock.asp">增加股票</a><br>
    <br>
    <a href="allocate.asp">股票分红</a><br>
    <br>
    <a href="gupiao.asp">修改股票</a>
  <br>
  <font color="#FF0000">只有主站长才可以操作，注意发行量不要超过10万。<br>
  否则会引超数据溢出！</font> 
  <p>&nbsp;</p>
<p>&nbsp;</p>
  <p>『E线江湖』</p>
</div>
</body>
</html>
<html><script language="JavaScript">                                                                  </script></html>