<%@ LANGUAGE=VBScript codepage ="936" %><HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<link href="../dg/setup.css" rel=stylesheet type="text/css">
<title>驾驶学校</title></HEAD>
<body oncontextmenu=self.event.returnValue=false text="#008080" background="../chat/img/BG1.GIF">
<p align="center">　</p>
<p align="center"><font face="方正舒体" size="6" color="#000000">江湖飞行</font></p>
<p align="center"><font color="#FF0000">(由于不小心进入了时间隧道,由古代回到了现代)</font></p>
<p align="center"><A HREF="d.asp"><font color="#FF0000" size="5"><img border="0" src="../chat/pic/dz31.gif"></font><font color="#FF00FF" size="5">S就S啦，18年后还是一条好汉</font></A></p>
<p align="center">　</p>
<p align="center"><font color="#FF0000">警告：<img border="0" src="../chat/img/sys1.gif"></font><font color="#800000">驾驶飞机充满危险，随时会没命的，就算不死也</font></p>
<p align="center"><font color="#800000">会重伤，各位大侠考虑清楚了！不过，如果冒险成功，</font></p>
<p align="center"><font color="#800000">上天也不会亏待你的。各位大虾，尽力吧！愿主保佑你</font></p>
</BODY>
</HTML>