<%@ LANGUAGE=VBScript codepage ="936" %><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<title>打工</title><link rel="stylesheet" href="../cn.css">
</head>
<body text="#000000" topmargin="4" background="../images/bg.gif">
<div align="center"> <font size="3" face="隶书"><font color="#000000" size="4">打工一条街</font></font><br>
<font size="2">可怜一个堂堂大侠，为了生计也只能去打工挣银两了</font>
<table border="3" width="600" cellspacing="2" bordercolor="#C0C0C0" height="101" bgcolor="#808080">
<tr bgcolor="#CCCCFF">
<td width="14%" height="14">
<p align="center"><font size="2" color="#000000">店小二</font>
</td>
      <td width="70%" height="14"><font size="2" color="#000000">考虑清楚哦，消耗体力100,薪水为4000两白花花的银子</font></td>
<td width="16%" align="center" height="14">
        <p align="center"><font size="2"><a href="dg1.asp">从事工作</a></font> 
      </td>
</tr>
<tr bgcolor="#CCCCFF">
<td width="14%" height="15">
<p align="center"><font size="2" color="#000000">搬运工</font>
</td>
<td width="70%" height="15"><font size="2" color="#000000">考虑清楚哦，消耗体力200,薪水为5000两白花花的银子</font></td>
      <td width="16%" align="center" height="15"><font size="2"><a href="dg2.asp">从事工作</a></font></td>
</tr>
<tr bgcolor="#CCCCFF">
<td width="14%" height="14">
<p align="center"><font size="2" color="#000000">官府衙差</font>
</td>
      <td width="70%" height="14"><font size="2" color="#000000">考虑清楚哦，消耗体力300,薪水为7000两白花花的银子</font></td>
      <td width="16%" align="center" height="14"><font size="2"><a href="dg3.asp">从事工作</a></font></td>
</tr>
<tr bgcolor="#CCCCFF">
<td width="14%" height="14">
<p align="center"><font size="2" color="#000000">保 镖</font>
</td>
<td width="70%" height="14"><font size="2" color="#000000">考虑清楚哦，消耗体力200,薪水为5000两白花花的银子</font></td>
      <td width="16%" align="center" height="14"><font size="2"><a href="dg4.asp">从事工作</a></font></td>
</tr>
<tr bgcolor="#CCCCFF">
<td width="14%" height="14">
<p align="center"><font size="2" color="#000000">皮条客</font>
</td>
<td width="70%" height="14"><font size="2" color="#000000">考虑清楚哦，消耗体力500,薪水为10000两白花花的银子(仅限俊男)</font></td>
      <td width="16%" align="center" height="14"><font size="2"><a href="dg5.asp">从事工作</a></font></td>
</tr>
<tr bgcolor="#CCCCFF">
<td width="14%" height="14">
<div align="center"><font size="2" color="#000000">怡红院 </font></div>
</td>
<td width="70%" height="14"><font size="2" color="#000000">考虑清楚哦，消耗体力500,薪水为10000两白花花的银子(仅限美女)</font></td>
      <td width="16%" align="center" height="14"><font size="2"><a href="dg6.asp">从事工作</a></font></td>
</tr>
</table>
<p> <font size="2">－ 这里是打工的地方，如果没钱,嘿，别急有一身力气还怕赚不到钱吗 </font>-<br>
    <font color="#FF0000"><b>打工刚刚开放，不过每小时只可以进行一次，可别累着</b>！</font><br>
</p>
<p></p>
</div>
</body>
</html>
