<%@ LANGUAGE=VBScript codepage ="936" %><%

sjjh_name=Session("sjjh_name")
sjjh_grade=Session("sjjh_grade")
sjjh_jhdj=Session("sjjh_jhdj")
chatbgcolor=Application("sjjh_chatbgcolor")
chatimage=Application("sjjh_chatimage")
if chatbgcolor="" then chatbgcolor="008888"
%>
<html>
<head>
<title>职业♀wWw.51eline.com♀</title>
<style type="text/css">
<!--
body {  font-size: 9pt;
scrollbar-track-color:#ffffff;
SCROLLBAR-FACE-COLOR:#effaff;
SCROLLBAR-HIGHLIGHT-COLOR:#ffffff;
SCROLLBAR-SHADOW-COLOR:#eeeeee;
SCROLLBAR-3DLIGHT-COLOR:#eeeeee;
SCROLLBAR-ARROW-COLOR:#dddddd;
SCROLLBAR-DARKSHADOW-COLOR:#ffffff
}
a:link {  text-decoration: none}
a:hover {  text-decoration: underline}
-->
</style>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head>
<body bgcolor="#006699" link="#0000FF" vlink="#0000FF" alink="#0000FF" leftmargin="0" topmargin="0" bgproperties="fixed" oncontextmenu=self.event.returnValue=false>
<table border="1" width="140" cellspacing="0" cellpadding="0" bgcolor="#006633" height="16" align="center" bordercolorlight="#000000" bordercolordark="#FFFFFF">
  <tr> 
    <td width="100%" height="28"> <div align="center"><font color="#ffffff" size="2">我的工作</font></div></td>
  </tr>
</table>
<table background="../bg2.gif" border="1" cellspacing="0" width="140" bordercolorlight="#000000"
bordercolordark="#FFFFFF" cellpadding="4" align="center">
  <tr> 
    <td><div align="center">
<font color="#006699">【</font></span></font><font size="3"><font color="#000000"><a href="#"onClick="window.open('../work/ice/icemain.asp','caibing','scrollbars=yes,resizable=yes,width=700,height=420')"
title="采冰赚钱！"><font color="#0000FF"> 采 冰</font> </a></font></font><font color="#006699"><font size="3">】</font></font><br>
<br>
<font color="#006699"><span style='font-size:9pt'><font size="3">【</font></span></font><font size="3">
<font color="#000000"><a href="#"onClick="window.open('../work/mine/minemain.asp','caikuang','scrollbars=yes,resizable=yes,width=700,height=420')"
title="采冰赚钱！"><font color="#0000FF"> 采 矿</font> </a></font></font><font color="#FFFFFF"><font size="3"></font></font><font color="#006699"><font size="3">】</font></font></p>
<p> <font color="#006699"><span style='font-size:9pt'><font size="3">【</font></span><font size="3" color="#000000">
</font><font size="3"><font color="#000000"><a href="#"onClick="window.open('../work/tie/tiemain.asp','liantie','scrollbars=yes,resizable=yes,width=700,height=420')"
title="采冰赚钱！"><font color="#0000FF"> 练 铁</font> </a></font></font><font color="#006699"><font size="3"></font></font><font size="3">】</font></font></p>
<p><font color="#006699"><span style='font-size:9pt'><font size="3">【</font></span><font size="3" color="#000000">
经 商 </font><font size="3">】</font></font></p>
<p><font color="#006699"><span style='font-size:9pt'><font size="3">【</font></span><font size="3" color="#000000">
教 师</font><font size="3"> 】</font></font><br></div>
</td>
  </tr>
  <tr>
<td bgcolor="#006633">
<font size="2" color="#cccccc">不同的职业可以有不同的收入，当然象道德、内力、体力、魅力等也是不相同的，大家可以根据喜好来选择自己的职业。</font>
</td>
  </tr>
</table>
</body>
</html>
