<head>
<link rel="stylesheet" href="../chatroom/css.css">
</head>
<body oncontextmenu=self.event.returnValue=false topmargin=100 background="../chatroom/bg1.gif">
<p align="center"><img border="0" src="../image/top13.gif" width="467" height="30"></p>
<p align="center">
欢迎使用辽西游戏网出品的快乐江湖！<br><br>
本程序速度快，可玩性高，绝对正点！<br><br>
任何人在没有作者的同意下请不要更改程序和版权！<br><br>
如有疑问可在<a href="http://yx8.net/forum.asp"><font color="#FF0000">游戏吧总站论坛</font></a>中提出提出!<br><br>
我们的快乐江湖正在一步步走向成熟<br><br>
最后谢谢您的使用！<br><br>

----<a target="_blank" href="http://yx8.net/">游戏吧</a>----</p>
<p align="center">　</p>
<p align="center">　</p>

</body>