<!-- 所有div先相对居中，再绝对置顶 -->
<div style="margin-left: auto;margin-right: auto;width:400px;" border=1>
<div style="position:absolute; left:370px; top:350px; width:332px; height:130px; z-index:2; background-image: url(home2.files/map/back.gif); layer-background-image: url(home2.files/map/back.gif); border: 1px none #000000; visibility: hidden;" id="Layer1">
<table width=100%><tr><td width=45><img src=home2.files/map/t1.gif></td><td>
<table width=100%>
<tr><td><a href=# onClick="window.open('hcjs/jhzb/index.asp','aqjh_win','scrollbars=0,resizable=0,width=700,height=400')">我的装备</A></td><td><a href=# onclick="window.open('hcjs/jhzb/myhua.asp','aqjh_win','scrollbars=0,resizable=0,width=430,height=340')">我的鲜花</a></td><td><a href=# onClick="window.open('JHMP/MP5.ASP','aqjh_win','scrollbars=0,resizable=0,width=690,height=440')">我的徒弟</a></td><td><a href=# onClick="window.open('hcjs/box/index.asp','aqjh_win','scrollbars=1,resizable=1,width=760,height=400')">我的储物</a></td</tr>
<tr><td><a href=# onClick="window.open('yamen/regmodi.asp','aqjh_win','scrollbars=1,resizable=0,width=480,height=470')">档案修改</a></td><td><a href=# onClick="window.open('yamen/editpass2.asp','aqjh_win','scrollbars=1,resizable=0,width=520,height=340')">密码保护</A></td><td><a href=# onClick="window.open('yamen/modify.asp','aqjh_win','scrollbars=1,resizable=0,width=520,height=340')">修改密码</a></td><td><a href=# onClick="window.open('hcjs/jhmtindex.asp','aqjh_win','width=550,height=410,resizable=0,scrollbars=0')">江湖密探</a></td></tr>
<tr><td><a href=# onClick="window.open('jhmp/wuguan.asp','aqjh_win','scrollbars=0,resizable=0,width=700,height=400')">江湖密室</a></td><td><a href=# onClick="window.open('HCJS/zstt/zs.asp','aqjh_win','scrollbars=0,resizable=0,width=690,height=440')">转世投胎</a></td><td><a href=# onClick="window.open('jhmp/money.asp','aqjh_win','scrollbars=0,resizable=0,width=430,height=440')">领取工资</a></td><td><a href=# onclick="window.open('yamen/gmhx.asp','aqjh_win','scrollbars=1,resizable=1,width=400,height=300')">更改姓名</a></td></tr>
<tr><td><a href=# onClick="window.open('jhmp/myfriend.asp','aqjh_win','scrollbars=1,resizable=1,width=700,height=400')">拉人记录</a></td><td><a href="#" onMouseDown="MM_showHideLayers('document.layers[\'Layer1\']','document.all[\'Layer1\']','hide')"><font color="yellow">关闭窗口</font></a></td></tr>
</table>
</td></tr></table>
</div>

<div style="position:absolute; left:370px; top:350px; width:332px; height:130px;  z-index:2; background-image: url(home2.files/map/back.gif); layer-background-image: url(home2.files/map/back.gif); border: 1px none #000000; visibility: hidden;" id="Layer2">
<table width=100%><tr><td width=45><img src=home2.files/map/t2.gif></td><td>
<table width=100%>
<tr><td><a href=# onClick="window.open('WORK/CATCH/CATCH.ASP','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">出海走私</A></td><td><a href=# onClick="window.open('twt/hit/DIAOYU.ASP','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">江湖飞行</A></td><td><a href=# onClick="window.open('twt/hunyin/killer.asp','aqjh_win','scrollbars=1,resizable=0,width=640,height=480')">雇佣杀手</A></td><td><a href=# onClick="window.open('twt/fengxue/fengxue.asp','aqjh_win','scrollbars=1,resizable=0,width=690,height=440')">风雪舞剑</a></td></tr><tr><td><a href=# onClick="window.open('twt/findbao/index.asp','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">孤岛冒险</A></td><td><a href=# onClick="window.open('twt/diaoyu/diaoyu.asp','aqjh_win','scrollbars=1,resizable=1,width=640,height=380')">休闲钓鱼</A></td><td><a href=# onClick="window.open('twt/grade/DIAOYU.ASP','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">江湖寻宝</A></td><td><a href=# onClick="window.open('twt/wokou/index.asp','aqjh_win','scrollbars=1,resizable=1,width=640,height=380')">抗击倭寇</A></td></tr><tr><td><a href=# onClick="window.open('twt/loot/loot.asp','aqjh_win','scrollbars=1,resizable=1,width=640,height=380')">抢劫银行</A></td><td><a href=# onClick="window.open('twt/hunyin/stunt.asp','aqjh_win','scrollbars=1,resizable=1,width=580,height=350')">合体特技</A></td><td><a href=# onClick="window.open('work/tie/tiemain.asp','aqjh_win','scrollbars=1,resizable=0,width=500,height=370')">矿石炼铁</a></td><td><a href=# onClick="window.open('work/mine/minemain.asp','aqjh_win','scrollbars=1,resizable=0,width=500,height=470')">江湖采矿</A></td></tr>
<tr><td><a href=# onClick="window.open('work/famu/famumain.asp','aqjh_win','scrollbars=1,resizable=0,width=600,height=370')">江湖伐木</A></td><td><a href=# onClick="window.open('work/ice/icemain.asp','aqjh_win','scrollbars=1,resizable=1,width=670,height=430')">江湖采冰</A></td><td><a href=# onClick="window.open('twt/tao/index.asp','aqjh_win','scrollbars=0,resizable=0,width=780,height=460')">江湖掏金</a></td><td><a href=# onclick="window.open('hcjs/dzwq/index.asp','aqjh_win','scrollbars=0,resizable=0,width=780,height=460')" >铸造武器</A></td></tr><tr><td><a href=# onClick="window.open('twt/peiyao/peiyao.asp','aqjh_win','scrollbars=0,resizable=0,width=780,height=460')">配药系统</A></td><td><a href="#" onMouseDown="MM_showHideLayers('document.layers[\'Layer2\']','document.all[\'Layer2\']','hide')"><font color="yellow">关闭窗口</font></a></td></tr>
</table>
</td></tr></table>
</div>
<div style="position:absolute; left:370px; top:350px; width:450px; height:150px;  z-index:2; background-image: url(home2.files/map/back.gif); layer-background-image: url(home2.files/map/back.gif); border: 1px none #000000; visibility: hidden;" id="Layer3">
<table width=100%><tr><td width=45><img src=home2.files/map/t3.gif></td><td>
<table width=100%>
<tr><td><a href="CHANGAN/xiaowu.asp" target=_blank>爱的小屋</A></td><td><a href=# onClick="window.open('hcjs/qr/index.asp','aqjh_win','scrollbars=1,resizable=0,width=650,height=450')">情人小筑</A></td><td><a href=# onClick="window.open('jhjd/jd.asp','aqjh_win','scrollbars=0,resizable=0,width=740,height=450')">江湖酒店</A></td><td><a href=# onClick="window.open('hcjs/pub/pub.asp','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">龙门客栈</A></td><td><a href=# onClick="window.open('hcjs/jhjs/hua.asp','aqjh_win','scrollbars=1,resizable=1,width=670,height=460')"">江湖花店</A></td><td><a href=# onClick="window.open('hcjs/jhjs/wuqi.asp','aqjh_win','scrollbars=0,resizable=0,width=650,height=550')">武器商店</A></td></tr>
<tr><td><a href=# onClick="window.open('hcjs/jhjs/anqi.asp','aqjh_win','scrollbars=1,resizable=0,width=740,height=400')">暗器商店</A></td><td><a href=# onClick="window.open('hcjs/jhjs/yaopu.asp','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">江湖药铺</A></td><td><a href=# onClick="window.open('hcjs/jhjs/vehicle.asp','aqjh_win','scrollbars=1,resizable=0,width=690,height=440')">交通工具</A></td><td><a href=# onClick="window.open('hcjs/jhjs/cw.asp','aqjh_win','scrollbars=0,resizable=0,width=520,height=450')">宠物商店</A></td><td><a href=# onClick="window.open('jhmp/maidou.asp','aqjh_win','scrollbars=1,resizable=1,width=320,height=340')">卖威力豆</a></td><td><a href=# onClick="window.open('hcjs/yilao.asp','aqjh_win','scrollbars=0,resizable=0,width=700,height=400')">蝶舞山庄</A></td></tr>
<tr><td><a href="xcj/xgn/sm.ASP" target="_blank">功能说明</A></td><td><a href=# onClick="window.open('xcj/zh/index.asp','aqjh_win','scrollbars=1,resizable=1,width=670,height=400')">转换市场</a></td><td><a href=# onClick="window.open('jhhy/laren/laren.asp','aqjh_win','scrollbars=1,resizable=0')">拉人奖励</A></td><td><a href=# onClick="window.open('jhhy/ydxx/DAJIA.ASP','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">造化三国</A></td><td><a href=# onClick="window.open('jhhy/liuyan/chakan.asp','aqjh_win','scrollbars=0,resizable=0,width=670,height=400')">留言站长</a></td><td><a href=# onClick="window.open('work/rw.asp','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">任务领取</A></td></tr>
<tr><td><a href=# onClick="window.open('hcjs/yhy/index.asp','aqjh_win','scrollbars=1,resizable=0,width=680,height=470')">超级妓院</A></td><td><a href=# onClick="window.open('hcjs/yhyb/index.asp','aqjh_win','scrollbars=1,resizable=1,width=780,height=460')">江湖鸭店</a></td><td><a href=# onClick="window.open('hcjs/qr/fkyy.asp','aqjh_win','scrollbars=1,resizable=0')">妇科中心</A></td><td><a href=# onClick="window.open('yamen/yiyuan.asp','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">江湖医院</A></td><td><a href=# onClick="window.open('garden/hua.htm','aqjh_win','scrollbars=0,resizable=0,width=670,height=400')">江湖花园</a></td><td><a href=# onClick="window.open('hcjs/jhjs/dan.asp','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">江湖当铺</A></td></tr>
<tr><td><a href=# onClick="window.open('CHANGAN/fangwu.asp','aqjh_win','scrollbars=1,resizable=0,width=740,height=450')">房产开发</A></td><td><a href=# onClick="window.open('hcjs/mj/mujuan.asp','aqjh_win','scrollbars=1,resizable=0,width=690,height=440')">江湖募捐</A></td><td><a href=# onClick="window.open('jhmp/gry.asp','aqjh_win','scrollbars=0,resizable=0,width=350,height=230')">救助孤儿</A></td><td><a href=# onClick="window.open('gupiao/stock.asp','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">股票市场</A></td><td><a href=# onClick="window.open('hcjs/dk/Daikuan.asp','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">高利贷款</A></td><td><a href=# onClick="window.open('hcjs/wish/wish.asp','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">江湖祈祷</A></td></tr>
<tr><td><a href=# onClick="window.open('twt/qq/read.htm','aqjh_win','scrollbars=1,resizable=0,width=540,height=480')">宣传奖励</A></td><td><a href=# onClick="window.open('work/changework.asp','aqjh_win','scrollbars=0,resizable=0,width=480,height=380')">职业转换</A></td><td><a href=# onClick="window.open('twt/dg/dg.asp','aqjh_win','scrollbars=1,resizable=1,width=670,height=400')">江湖打工</a></td><td><a href=# onClick="window.open('hcjs/xuewu/xuetang.htm','aqjh_win','scrollbars=1,resizable=1,width=640,height=380')">武馆习武</A></td><td><a href=# onClick="window.open('twt/hunyin/index.asp','aqjh_win','scrollbars=0,resizable=0,width=550,height=450')">江湖月老</A></td><td><a href=# onClick="window.open('twt/hunyin/taohun.asp','aqjh_win','scrollbars=1,resizable=1,width=640,height=380')">江湖逃婚</A></td></tr>
<tr><td><a href=# onClick="window.open('bet/betindex.asp','aqjh_win','scrollbars=0,resizable=0,width=700,height=400')">江湖赌馆</A></td><td><a href=# onClick="window.open('myhome/house.asp','aqjh_win','scrollbars=0,resizable=0,width=650,height=400')">花园别墅</A></td><td><a href=# onClick="window.open('hcjs/mc/index.asp','aqjh_win','scrollbars=1,resizable=1,width=670,height=400')">清理粪库</a></td><td><a href=# onClick="window.open('work/changeworkzhongzu.asp','aqjh_win','scrollbars=1,resizable=1,width=700,height=400')">种族变身</a></td><td><a href="#" onMouseDown="MM_showHideLayers('document.layers[\'Layer3\']','document.all[\'Layer3\']','hide')"><font color="yellow">关闭窗口</font></a></td><td></td></tr>
</table>
</td></tr></table>
</div>
<div style="position:absolute; left:370px; top:350px; width:332px; height:130px; z-index:2; background-image: url(home2.files/map/back.gif); layer-background-image: url(home2.files/map/back.gif); border: 1px none #000000; visibility: hidden;" id="Layer4">
<table width=100%><tr><td width=45><img src=home2.files/map/t4.gif></td><td>
<table width=100%>
<tr align=center><td><a href=# onClick="window.open('jhmp/index.asp','aqjh_win','scrollbars=1,resizable=0,width=760,height=450')">七门八派</A></td><td><a href=# onClick="window.open('jhmp/setwg.asp','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">武功设置</A></td></tr>
<tr align=center><td><a href=# onClick="window.open('jhmp/addmp/chuangp.asp','aqjh_win','scrollbars=1,resizable=0,width=550,height=450')">自立门派</a></td><td><a href=# onClick="window.open('jhmp/addmp/rangwei.asp','aqjh_win','scrollbars=1,resizable=1,width=580,height=350')">掌门让位</A></td></tr>
<tr align=center><td><a href=# onClick="window.open('hcjs/room/index.asp','aqjh_win','scrollbars=1,resizable=0,width=600,height=450')">自创房间</a></td><td><a href=# onclick="window.open('jhmp/mympjj.asp','aqjh_win','scrollbars=1,resizable=1,width=320,height=340')" target=_self>门派基金</A></td></tr>
<tr align=center><td><a href="#" onMouseDown="MM_showHideLayers('document.layers[\'Layer4\']','document.all[\'Layer4\']','hide')"><font color="yellow">关闭窗口</font></a></td><td></td></tr>
</table>
</td></tr></table>
</div>
<div style="position:absolute; left:370px; top:350px; width:332px; height:130px; z-index:2; background-image: url(home2.files/map/back.gif); layer-background-image: url(home2.files/map/back.gif); border: 1px none #000000; visibility: hidden;" id="Layer5">
<table width=100%><tr><td width=45><img src=home2.files/map/t5.gif></td><td>
<table width=100%>
<tr align=center><td><a href=# onClick="window.open('yamen/admin.asp','aqjh_win','scrollbars=0,resizable=0,width=740,height=450')">网管名单</A></td><td><a href=# onClick="window.open('yamen/laofan.asp','aqjh_win','scrollbars=0,resizable=0,width=700,height=400')">江湖天牢</A></td></tr>
<tr align=center><td><a href=# onClick="window.open('jhmp/poll/poll.asp','aqjh_win','scrollbars=0,resizable=0,width=740,height=450')">江湖选举</A></td><td><a href=# onClick="window.open('twt/pingding/pingd.asp','aqjh_win','scrollbars=0,resizable=0,width=700,height=400')">管理评定</A></td></tr>
<tr align=center><td><a href=# onClick="window.open('yamen/minan.asp','aqjh_win','scrollbars=0,resizable=0,width=700,height=470')">命案查询</A></td><td><a href=# onClick="window.open('jl/jlmain.asp','aqjh_win','scrollbars=1,resizable=0,width=740,height=450')">江湖大事</A></td></tr>
<tr align=center><td><a href=# onClick="window.open('yamen/laofan1.asp','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">睡眠解救</A></td><td><a href=# onClick="window.open('hcjs/sy/sy.htm','aqjh_win','scrollbars=0,resizable=0,width=700,height=420')">击鼓鸣冤</A></td></tr>
<tr align=center><td><a href=# onClick="window.open('yamen/laofang2.asp','aqjh_win','scrollbars=0,resizable=0,width=620,height=400')">查看监禁</A></td><td><a href="#" onMouseDown="MM_showHideLayers('document.layers[\'Layer5\']','document.all[\'Layer5\']','hide')"><font color="yellow">关闭窗口</font></a></td></tr>
</table>
</td></tr></table>
</div>
<div style="position:absolute; left:370px; top:350px; width:332px; height:130px; z-index:2; background-image: url(home2.files/map/back.gif); layer-background-image: url(home2.files/map/back.gif); border: 1px none #000000; visibility: hidden;" id="Layer6">
<table width=100%><tr><td width=45><img src=home2.files/map/t6.gif></td><td>
<table width=100%>
<tr><td><a href="chat/hy.asp" target=_blank>购买会员</A></td><td><a href=# onClick="window.open('jhmp/hy.asp','aqjh_win','scrollbars=1,resizable=0,width=680,height=470')">会员列表</A></td><td><a href=# onClick="window.open('hcjs/card/card.asp','aqjh_win','scrollbars=1,resizable=0,width=700,height=400')">会员卡片</A></td></tr>
<tr><td><a href=# onClick="window.open('jhhy/workauto/ice/icemain.asp','aqjh_win','scrollbars=1,resizable=1,width=670,height=430')">会员采冰</A></td><td><a href=# onClick="window.open('jhhy/hyxuewu/index.asp','aqjh_win','scrollbars=1,resizable=0,width=700,height=450')">会员学武</a></td><td><a href=# onClick="window.open('jhhy/xiang/index.asp','aqjh_win','scrollbars=1,resizable=0,width=680,height=470')">会员拜神</a></td></tr>
<tr><td><a href=# onClick="window.open('jhhy/workauto/famu/famumain.asp','aqjh_win','scrollbars=1,resizable=0,width=600,height=370')">会员伐木</A></td><td><a href=# onClick="window.open('jhhy/workauto/mine/minemain.asp','aqjh_win','scrollbars=1,resizable=0,width=500,height=450')">会员采矿</A></td><td><a href=# onClick="window.open('jhhy/hywabao/wabao.asp','aqjh_win','scrollbars=1,resizable=0,width=500,height=450')">会员挖宝</a></td></tr>
<tr><td><a href="#" onMouseDown="MM_showHideLayers('document.layers[\'Layer6\']','document.all[\'Layer6\']','hide')"><font color="yellow">关闭窗口</font></a></td><td></td></tr>
</table>
</td></tr></table>
</div>
</div>