<HTML><HEAD>
<META http-equiv=Content-Type content="text/html; charset=gb2312">
<META content="MSHTML 6.00.2600.0" name=GENERATOR><title>江湖秀形像代码</title></HEAD>
<BODY bgColor=#f9a20a leftMargin=0 topMargin=0>
<div align="center">
  <table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr align="center"> 
      <td colspan="2">江湖秀形像代码 </td>
    </tr>
    <tr align="center"> 
      <td colspan="2"> 
        <textarea name="textarea" cols="68" rows="2"><script language=javascript src=disp.asp?name=<%=session("aqjh_name")%>&id=0></script></textarea>
      </td>
    </tr>
    <tr> 
      <td width="74%" height="42" valign="top">在这里你可以把你自己的形像资料引入在其它网站使用， 图片大小140*226，其中name为姓名,当id为0时为你当前所装备头像,当为1-9时为像册中所保存的图像(非会员3张)！ 
        将以上代码，复制到你网站上你就可以有如图所求照片 ：</td>
      <td width="26%"><img src="images/demo.gif" width="140" height="254"></td>
    </tr>
  </table>
</div>
</BODY></HTML>
