<html>
<head>
<title>渔人码头</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<LINK href="../../style2.css" type=text/css rel=stylesheet>

</head>
<body bgcolor="#000000" text="#FFFFFF" oncontextmenu=self.event.returnValue=false>
<p align="center">　</p>
<div align="center">
<center>
<table cellspacing=0 cellpadding=0 width=501
border=0 bgcolor="#000000">
<tr>
<TD vAlign=top align=middle width=16 rowSpan=8><IMG
src="../../image/dragon.gif"><BR><IMG
src="../../image/line.gif"><BR><BR><IMG
src="../../image/arrow.gif"> </TD>
<td valign=top width=168 height="241">
<p><img border="0" src="Untitled.gif"></p>
</td>
<td width=23 height="241"><img height=1 src="index.files/0.gif"
width=1></td>
<td class=ct-def1
width=310 height="241">
<p><font color="#FFFFFF">欢迎您来到剑侠情缘渔人码头！<br>
一种心情，一个机会；<br>
一份辛劳，双重收获。 <br>
带上称手的家伙，从这里出发，去钓鱼喽！</font></p>
</center>
<p align="left"><font color="#FFFF00">&nbsp; 注：每次钓鱼时间为2分钟即120秒，上钩后15秒不拉杆就会溜走钓鱼的成功的几率是10%，大家看见河里有动静了鼠标点动的地方，就可以掉到钓到的鱼功能可是很强的哦！<br>  
</font>  
</p>  
<center>  
<table cellspacing=0 cellpadding=0 width=250 align=center  
border=0>  
<tbody>  
<tr>  
<td class=ct-def1>当前职业：　钓鱼</td>  
</tr>  
<tr>  
<td class=ct-def1>技能级别：　新手</td>  
</tr>  
<tr>  
<td class=ct-def1>工作地点：　渔人码头</td>  
</tr>  
<tr>  
<td class=ct-def1 align=right><a href="#" onclick="javascript:tiewin=window.open('diao.asp','diaole','scrollbars=no,resizable=yes,width=700,height=420');" onmouseover="window.status='';return true;" onmouseout="window.status='';return true;" title>进入</a><img 
height=20 src="gonext.gif" width=42 
border=0></td> 
</tr> 
</tbody> 
</table> 
</center> 
</td> 
<TD vAlign=top align=middle width=16 rowSpan=8><IMG 
src="../../image/dragon.gif"><BR><IMG 
src="../../image/line.gif"><BR><BR><IMG 
src="../../image/arrow.gif"> </TD> 
</tr> 
</table> 
</div> 
</body> 
</html> 
 
