<HTML><HEAD><TITLE>战将注册</TITLE>
<META content="text/html; charset=gb2312" http-equiv=Content-Type><LINK 
href="reg/clubcom.css" rel=stylesheet type=text/css>
<META content="Microsoft FrontPage 5.0" name=GENERATOR></HEAD>
<BODY bgColor=#000000 text=#ffffff topMargin=0>
<TABLE align=center border=0 cellPadding=0 cellSpacing=0 width=596>
  <TBODY> 
  <TR>
    <TD background=reg/history_table_bg.gif height=158 vAlign=top width="596"> 
      <div align="center">
        <center> 
      <TABLE border=10 cellPadding=0 cellSpacing=0 class=mountain 
      width=596 height="153" bordercolor="#840000" style="border-collapse: collapse; background-image:url('reg/page_bottom_mountain.gif')">
        <TBODY> 
        <TR>
          <TD vAlign=top bgcolor="#000000" height="19">
          <table align="center" border="0" cellPadding="0" cellSpacing="0" width="596">
            <tr>
              <td background="reg/history_top_bg.gif" vAlign="top" width="596">
              <table align="center" border="0" cellPadding="2" cellSpacing="0" class="p9" width="97%" height="24">
                <tr>
                  <td height="20" width="31%">　</td>
                  <td height="20" vAlign="top" width="37%">
                  <div align="center">
                    <font color="#FF0000" size="3">魔幻战将注册</font></div>
                  </td>
                  <td height="20" vAlign="top" width="32%">　</td>
                </tr>
              </table>
              </td>
            </tr>
          </table>
          </TD></TR> 
        <TR>
          <TD vAlign=top bgcolor="#000000" height="30" bordercolor="#000000">
          <p align="center"><img border="0" src="reg/top1.gif"></TD></TR> 
        <TR>
          <TD vAlign=top bgcolor="#000000" height="45" bordercolor="#000000">
            <div align="center">
              <center>
            <TABLE background=reg/table_bg.gif border=0 
            cellPadding=0 cellSpacing=0 class=p9 width="537" height="321" style="border-collapse: collapse">
              <TBODY> 
              <TR>
                <TD align=left vAlign=top height="21" width="537"> 
                  <class=p9><font color="#FF0000"><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 【江湖提示】&nbsp; </b></font><br>
                          　　<font color="#FFFF00">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 精力10万、精力50万、体力1000万、内力50万<br>
                  </font>用户在申请和使用本系统时，必须遵守以下规则：<br>
                  （1）用户对所申请的帐号和密码安全负全部责任；<br>
                  （2）用户对该帐户中的所有活动和事件负全部责任；
                  <blockquote>
                    <p>同时包括：<br>
                    用户不得发布任何非法的、骚扰性的、中伤他人的、辱骂性的、恐吓性的、伤害性的、庸俗的，淫秽等信息资料；<br>
                    用户不能发布任何教唆他人构成犯罪行为的资料；<br>
                    用户不能发布任何不符合当地法规、国家法律和国际法律的资料；<br>
                    若用户的行为不符合以上提到的服务条款将作出独立判断立即取消用户帐号。</p>
                  </blockquote>
                  <p>（3）同意承担系统由于管理、升级等因素造成的数据库清零(删除帐号)的风险；<br>
                  （4）用户若反对任何服务条款、对后来的条款修改有异议，或对服务不满，用户有以下权利：</p>
                  <blockquote>
                   （a）不再使用本系统游戏；<br>
                    （b）通告停止该用户的使用。

                  </blockquote>
                  <p align="center">
                  <a href="regstep2.asp" style="color: #FFA418; text-decoration: none; background-color: none">
                  <font color="#FF9900">[同意协议]</font></a> 　　<a href="javascript:top.window.close();" style="color: #FFA418; text-decoration: none; background-color: none"><font color="#FF9900">[拒绝协议]</font></a></p>
                  </TD></p></TR></TBODY></TABLE>
              </center>
          </div>
            </TD></TR> 
        <TR>
          <TD vAlign=top bgcolor="#000000" height="44">
          <p align="center"><img border="0" src="reg/top3.gif"></TD></TR></TBODY></TABLE></center>
      </div>
    </TD></TR>
  <TR>
    <TD bgColor=#847939 height=1 width="596"><IMG height=1 src="reg/page_point.gif" 
      width=1></TD>
  </TR></TBODY></TABLE></BODY></HTML>