<HTML><HEAD><TITLE>战将注册</TITLE>
<META content="text/html; charset=gb2312" http-equiv=Content-Type><LINK 
href="reg/clubcom.css" rel=stylesheet type=text/css>
<META content="Microsoft FrontPage 5.0" name=GENERATOR></HEAD>
<BODY bgColor=#000000 text=#ffffff topMargin=40>
<TABLE align=center border=0 cellPadding=0 cellSpacing=0 width=596>
  <TBODY> 
  <TR>
    <TD background=reg/history_table_bg.gif height=158 vAlign=top width="596"> 
      <div align="center">
        <center> 
      <TABLE border=10 cellPadding=0 cellSpacing=0 class=mountain 
      width=596 height="212" bordercolor="#840000" style="border-collapse: collapse; background-image:url('reg/page_bottom_mountain.gif')">
        <TBODY> 
        <TR>
          <TD vAlign=top bgcolor="#000000" height="19" bordercolor="#000000">
          <table align="center" border="0" cellPadding="0" cellSpacing="0" width="596">
            <tr>
              <td background="reg/history_top_bg.gif" vAlign="top" width="596">
              <table align="center" border="0" cellPadding="2" cellSpacing="0" class="p9" width="97%" height="24">
                <tr>
                  <td height="20" width="31%">　</td>
                  <td height="20" vAlign="top" width="37%">
                  <div align="center">
                    <font color="#FF0000" size="3">魔幻战将注册</font></div>
                  </td>
                  <td height="20" vAlign="top" width="32%">　</td>
                </tr>
              </table>
              </td>
            </tr>
          </table>
          </TD></TR> 
        <body leftmargin="0"  marginwidth="0" marginheight="0" bgcolor="#804040" topmargin="40">
<form action="regstep3.asp" method="post" id=form1 name=form1>

        <TR>
          <TD vAlign=top bgcolor="#000000" height="45" bordercolor="#000000">
          &nbsp;&nbsp;&nbsp;&nbsp;<align="center"><img border="0" src="reg/top1.gif">
            <div align="center">
              <center>
            <TABLE background=reg/table_bg.gif border=0 
            cellPadding=0 cellSpacing=0 class=p9 width="537" height="240" style="border-collapse: collapse">
              <TBODY> 
              <TR>
               <td height="25" width="71" align="center">帐号<font color="#FF0080"> 
               *</font></td>       
              <td height="25" width="276"> &nbsp;        
                <input name="account" maxlength=14 size=14 style="text-decoration: blink; border: 1px solid #804040" onMouseOver="this.style.backgroundColor = '#FFCC00'" onMouseOut="this.style.backgroundColor = '#FFFFFF'"> 
              6-14位数字或字母</td>       
            </tr>       
            <tr>        
              <td height="25" width="71" align="center">姓名<font color="#FF0080"> 
              *</font></td>       
              <td height="25" width="276"> &nbsp;        
                <input name="username" maxlength=6 size="14" style="text-decoration: blink; border: 1px solid #804040" onMouseOver="this.style.backgroundColor = '#FFCC00'" onMouseOut="this.style.backgroundColor = '#FFFFFF'"> 
              2-5位以上中文名</td>      
            </tr>      
            <tr>       
              <td height="25" width="71" align="center">密码<font color="#FF0080"> 
              *</font></td>       
              <td height="25" width="276"> &nbsp;        
                <input type="password" name="password" maxlength=14 size=14 style="text-decoration: blink; border: 1px solid #804040" onMouseOver="this.style.backgroundColor = '#FFCC00'" onMouseOut="this.style.backgroundColor = '#FFFFFF'"> 
              6-14位数字或字母</td>       
            </tr>       
            <tr>        
              <td height="25" width="71" align="center">确认<font color="#FF0080"> 
              *</font></td>       
              <td height="25" width="276"> &nbsp;        
                <input type="password" name="repassword" maxlength=14 size=14 style="text-decoration: blink; border: 1px solid #804040" onMouseOver="this.style.backgroundColor = '#FFCC00'" onMouseOut="this.style.backgroundColor = '#FFFFFF'"> 
              再输入一遍密码，避免错误</td>       
            </tr>       
            <tr>        
              <td height="25" width="71" align="center">介绍人</td>       
              <td height="25" width="276"> &nbsp;        
                <input name="jsr" size="14" maxlength="10" style="text-decoration: blink; border: 1px solid #804040" onMouseOver="this.style.backgroundColor = '#FFCC00'" onMouseOut="this.style.backgroundColor = '#FFFFFF'"> 
              此项为可选项,可填可不填</td>       
            </tr>       
            <tr>        
              <td height="25" width="71" align="center">性别<font color="#FF0080"> 
              *</font></td>       
              <td height="25" width="276"> &nbsp;        
                <select name="sex">       
                  <option value="" selected>请选择</option>
                  <option value="男">男侠客</option>
                  <option value="女">女侠客</option>
                </select>
              </td>
            </tr>
            <tr> 
              <td height="25" width="71" align="center">国家<font color="#FF0080"> 
              *</font></td>       
              <td height="25" width="276"> &nbsp;        
                <select name="country">       
                  <option value="" selected>请选择</option>
                  <option value="秦">秦国</option>
                  <option value="楚">楚国</option>
                  <option value="赵">赵国</option>
                  <option value="魏">魏国</option>
                  <option value="齐">齐国</option>
                  <option value="韩">韩国</option>
                  <option value="燕">燕国</option>
                </select> 一个好的国家，君主会发好多银子</td>
            </tr>
            <tr> 
              <td colspan="2" height="1" width="357"> 
              <p align="left">&nbsp;&nbsp; 
              <img id=face src="../face/006.gif" alt=个人形象代表>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        
                <select name=txxx size=1 onChange="document.images['face'].src=options[selectedIndex].value;">       
                  <option selected value="../face/001.gif">形象1        
                  <option value="../face/002.gif">形象2        
                  <option value="../face/003.gif">形象3        
                  <option value="../face/004.gif">形象4        
                  <option value="../face/005.gif">形象5        
                  <option value="../face/006.gif">形象6        
                  <option value="../face/007.gif">形象7        
                  <option value="../face/008.gif">形象8        
                  <option value="../face/009.gif">形象9        
                  <option value="../face/010.gif">形象10        
                  <option value="../face/012.gif">形象11        
                  <option value="../face/013.gif">形象12        
                  <option value="../face/014.gif">形象13        
                  <option value="../face/015.gif">形象14        
                  <option value="../face/016.gif">形象15        
                  <option value="../face/017.gif">形象16        
                  <option value="../face/018.gif">形象17        
                  <option value="../face/019.gif">形象18        
                  <option value="../face/020.gif">形象19        
                  <option value="../face/021.gif">形象20        
                  <option value="../face/022.gif">形象21        
                  <option value="../face/023.gif">形象22        
                  <option value="../face/024.gif">形象23        
                  <option value="../face/025.gif">形象24        
                  <option value="../face/026.gif">形象25        
                  <option value="../face/027.gif">形象26        
                  <option value="../face/028.gif">形象27        
                  <option value="../face/029.gif">形象28        
                  <option value="../face/030.gif">形象29        
                  <option value="../face/031.gif">形象30        
                  <option value="../face/032.gif">形象31        
                  <option value="../face/033.gif">形象32        
                  <option value="../face/034.gif">形象33        
                  <option value="../face/035.gif">形象34        
                  <option value="../face/036.gif">形象35        
                  <option value="../face/037.gif">形象36        
                  <option value="../face/038.gif">形象37        
                  <option value="../face/039.gif">形象38        
                  <option value="../face/040.gif">形象39        
                  <option value="../face/041.gif">形象40        
                  <option value="../face/042.gif">形象41        
                  <option value="../face/043.gif">形象42        
                  <option value="../face/044.gif">形象43        
                  <option value="../face/045.gif">形象44        
                  <option value="../face/046.gif">形象45        
                  <option value="../face/047.gif">形象46        
                  <option value="../face/048.gif">形象47        
                  <option value="../face/049.gif">形象48        
                  <option value="../face/050.gif">形象49        
                  <option value="../face/051.gif">形象50        
                  <option value="../face/052.gif">形象51        
                  <option value="../face/053.gif">形象52        
                  <option value="../face/054.gif">形象53        
                  <option value="../face/055.gif">形象54        
                  <option value="../face/056.gif">形象55        
                  <option value="../face/057.gif">形象56        
                  <option value="../face/058.gif">形象57        
                  <option value="../face/059.gif">形象58        
                  <option value="../face/060.gif">形象59        
                  <option value="../face/061.gif">形象60        
                  <option value="../face/062.gif">形象61        
                  <option value="../face/063.gif">形象62        
                  <option value="../face/064.gif">形象63        
                  <option value="../face/065.gif">形象64        
                  <option value="../face/066.gif">形象65        
                  <option value="../face/067.gif">形象66        
                  <option value="../face/068.gif">形象67        
                  <option value="../face/069.gif">形象68        
                  <option value="../face/070.gif">形象69        
                  <option value="../face/071.gif">形象70        
                  <option value="../face/072.gif">形象71        
                  <option value="../face/073.gif">形象72        
                  <option value="../face/074.gif">形象72        
                  <option value="../face/075.gif">形象74        
                  <option value="../face/076.gif">形象75        
                  <option value="../face/077.gif">形象76        
                  <option value="../face/078.gif">形象77        
                  <option value="../face/079.gif">形象78        
                  <option value="../face/080.gif">形象79        
                  <option value="../face/081.gif">形象80        
                  <option value="../face/082.gif">形象81        
                  <option value="../face/083.gif">形象82        
                  <option value="../face/084.gif">形象83        
                  <option value="../face/085.gif">形象84        
                  <option value="../face/086.gif">形象85        
                  <option value="../face/087.gif">形象86        
                  <option value="../face/088.gif">形象87        
                  <option value="../face/089.gif">形象88        
                  <option value="../face/090.gif">形象89        
                  <option value="../face/091.gif">形象90        
                  <option value="../face/092.gif">形象91        
                  <option value="../face/093.gif">形象92        
                  <option value="../face/094.gif">形象93        
                  <option value="../face/095.gif">形象94        
                  <option value="../face/096.gif">形象95        
                  <option value="../face/097.gif">形象96        
                  <option value="../face/098.gif">形象97        
                  <option value="../face/099.gif">形象98        
                  <option value="../face/100.gif">形象99        
                </select> 进入聊天室头像 </td>       
            </tr>       
            <tr>        
              <td colspan=2 align=middle height="21" width="357">        
                <div align="center" style="width: 533; height: 60">        
                  <p>　</p>       
                  <p>        
                    <input type="submit" value=" 注 册 " name="submit">       
                    <input type="reset" value=" 重 填 " name="reset">       
                    <input type="button" value=" 关 闭 " onClick="javascript:top.window.close();" name="button">       
                  </p>       
                </div>       
              </td>       
</font></a></p>
                  </TD></p></TR></TBODY></TABLE>
              </center>
          </div>
            </TD></TR>

        <TR>
          <TD vAlign=top bgcolor="#000000" height="44" bordercolor="#000000">
          <p align="center"><img border="0" src="reg/top3.gif"></TD></TR></TBODY></TABLE></center>
      </div>
    </TD></TR>
  <TR>
    <TD bgColor=#847939 height=1 width="596"><IMG height=1 src="reg/page_point.gif" 
      width=1></TD>
  </TR></TBODY></TABLE></BODY></HTML>