
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>我的武功</title>
<link rel="stylesheet" href="../style5.css">
</head>

<body bgcolor="#000000" text="#FFFFFF">

<div align="center">
<center>
<table border="0" cellpadding="0" cellspacing="0" width="270" height="291">
<tr>
<td width="268" height="293" background="../image/wygong.gif">　</td>
</tr>
</table>
</center>
</div>
<div id="Layer1" style="z-index: 1; width: 227; position: absolute; height: 150; left: 295; top: 65">
<iframe
border=0 frameborder=0 framespacing=0 height=150 marginheight=0
marginwidth=0 name=new_date noResize scrolling=yes
src="wugong2.asp" width=200 vspale="1"></iframe>
</div>
<div id="Layer2" style="z-index: 2; width: 222; position: absolute; height: 65; left: 281; top: 231">
以无法为有法，以无限为有限
<p align="center">此为武术的最高境界
</div>
</body>

