<html>
<head>
</head>
<body>
<form method="POST" action="search.asp">
  <div align="center"> 
    点歌查询系统： 
    <select name="sjcz"> 
      <option value="歌名" selected>歌曲</option> 
      <option value="歌手">歌手</option> 
    </select> 
    <input type="text" name="search" size="20" maxlength="20">      
    <input type="submit" value="查询" name="B1" class="p9">      
    <input type="reset" name="Submit" value="清空">      
  </div>        
  </form> 
</body> 
</html> 
 
