<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title><%=Application("sjjh_chatroomname")%>会员充值系统</title>
</head>

<body bgcolor="#EBFFD7" background="bg.gif" oncontextmenu="return false;" onselectstart="return false">
<p align="center">
<font color="#FF0000" size="6"><b><%=Application("sjjh_chatroomname")%>会员充值卡</b></font><p align="left"><font color="#FF0000" size="4"><b>充值卡的用途：</b></font><p align="left"><font color="#0000FF">1张充值卡=5000存点&nbsp;&nbsp;&nbsp;&nbsp;    
</font><a href="czk1.asp"><font color="#FF0000">点击充值存点</font></a><p align="left"><font color="#0000FF">1张充值卡=5元金卡&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font><font color="#0000FF">  
</font><a href="czk2.asp"><font color="#FF0000">点击充值金卡</font></a><p align="left"><font color="#0000FF">1张充值卡=100个金币&nbsp;&nbsp;&nbsp;</font><font color="#0000FF">  
</font><a href="czk3.asp"><font color="#FF0000">点击充值金币</font></a><p align="left"><font color="#0000FF">1张充值卡=10000个银币&nbsp;</font><font color="#0000FF">  
</font><a href="czk4.asp"><font color="#FF0000">点击充值银币</font></a><p align="left"><font color="#0000FF">充值卡可以充值会员日期和会员等级。&nbsp;    
</font><a href="zhuan.asp"><font color="#FF0000">点击充值会员</font></a><font color="#FF0000">&nbsp;    
</font><a href="../taiqiu/zh.asp"><font color="#FF0000">点击进入转换市场</font></a>
</body>    
</html>    
