<html>
<head>
<title>极地采冰</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<base target="_self">
</head>
<body bgcolor="#000000" text="#FFFFFF" topmargin="0" link="#0000FF" vlink="#0000FF" alink="#0000FF" style="font-size: 9px">
<div align="center" style="width: 84; height: 173">
  <table width="84" border="1" cellpadding="0" cellspacing="0">
    <tr> 
      <td height="11" style="font-size: 9pt"> 
        <div align="center"><font><a href="maiice.asp" target="cz1">
          <font color="#FF0000">卖冰</font></a></font></div>
      </td>
    </tr>
    <tr> 
      <td height="37" align="left" valign="top" style="font-size: 9pt">
      <font color="#FFFF00">一桶冰的价钱20000两，选择卖冰可以冰水转换成银两！</font></td>
    </tr>
    <tr>
      <td height="9" align="left" valign="top" style="font-size: 9pt">
        <div align="center"><font><a href="saveice.asp" target="cz1">
          <font color="#FF0000">保存</font></a></font></div>
      </td>
    </tr>
    <tr>
      <td height="74" align="left" valign="top" style="font-size: 9pt">
      <font color="#FFFF00">保存，可以把冰水存放到家里，可以自己服用，体内、力内各加10000</font></td>
    </tr>
  </table>
</div>
</body>
</html>