<html>
<head>
<title>爱情江湖养猪说明</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
</head>

<body bgcolor="#FFFFFF" text="#000000">
<table cellspacing=0 cellpadding=0 width="95%" align=center 
border=0 background="images/dw.gif">
  <tbody> 
  <tr> 
      <td class=bbs valign="top" height="1023"><b><font color="red">江湖新增加了种花功能。下面我来说说怎样去你的花园‘种花’。</font></b> 
        <p><b><font 
                  color=blue>刚来到江湖，注册时站长就送您3颗种子，在江湖上面找到花园的联接点击进入，便可以种值自己的花园了！<br>
        </font></b><img 
                  src="images/button7.gif"><b><font color="#0000FF">开垦，如果你没有种子了，用他重新开垦(原有花全部清除，系统自动给您1颗种子)</font><br>
        </b><b></b><b></b><img 
                  src="images/button5.gif"><b><font 
                  color=blue>播种，如果网速正常,幼苗很快就会出现。点一下你的幼苗，看看它现在需要什么.你就可以去点什么去照顾她。</font></b><br>
        <b>例如；</b><br>
        <img 
                  src="images/a2.gif" width="14" height="14"><b><font color=blue>这是需要施肥；你就可以点</font></b><img 
                  src="images/button2.gif"><b><font 
                  color=blue>施肥.</font></b><br>
        <img src="images/a1.gif" width="14" height="14"><b><font 
                  color=blue>这是需要浇水;你就可以点</font></b><img 
                  src="images/button3.gif"><b><font 
                  color=blue>浇水.</font></b><br>
        <img src="images/a3.gif" width="14" height="14"><b><font 
                  color=blue>这是需要剪枝;你就可以点</font></b><img 
                  src="images/button4.gif"><b><font 
                  color=blue>剪枝.</font></b><br>
        <img src="images/a4.gif" width="14" height="14"><b><font 
                  color=blue>这是需要除虫;你就可以点</font></b><img 
                  src="images/button1.gif"><b><font 
                  color=blue>除虫</font></b><br>
        <img src="images/a5.gif" width="14" height="14"><b><font 
                  color=blue>这是可以收获了;你就可以点</font></b><font color=blue><img 
                  src="images/button6.gif"></font><b><font 
                  color=blue>采摘</font></b> <br>
        <b><font 
                  color=blue>要提高它的成熟度,必须进行它需要的操作，否则是无效的。前一次操作完成以后<br>
        ,一般需要过120秒才能进行下一次操作，在这之间花苗需要休息，所以心急是没有用的。<br>
        成熟度每到25的倍数时,幼苗会长大一次,当成熟度达到50的时候，您可以看到这株花的颜色<br>
        。现在共有5种颜色可能出现：<br>
        紫色－逸韵</font></b><img 
                  src="images/flower54.gif"><b><font 
                  color=blue><br>
        白色－冰雪</font></b><img 
                  src="images/flower53.gif"><b><font 
                  color=blue><br>
        粉色－香芸</font></b><img 
                  src="images/flower52.gif"><b><font 
                  color=blue><br>
        黄色－忧梦</font></b><img 
                  src="images/flower51.gif"><b><font 
                  color=blue><br>
        红色－烈焰</font></b><img 
                  src="images/flower50.gif">；<b><font 
                  color=blue>每种颜色出现的几率是不一样的，而<br>
        且花的颜色不能通过种子100%遗传给下一代，所以得到什么样的花，就看您的运气了。<br>
        等成熟度达到100,需要收获的时候</font></b><img 
                  src="images/a5.gif" width="14" height="14">,<b><font color=blue>点(收获)</font></b><font color=blue><img 
                  src="images/button6.gif">,<b><font 
                  color=blue>就出来一个对话框,这时您选择"取消"是收获3颗种子,花当然就没有了;选择"确定"是收获鲜花。烈焰--忧梦--香芸--冰雪--逸韵，收获的种子在苗圃里可以看到</font></b><img 
                  src="images/02.gif">，<b><font 
                  color=blue>供继续种花使用，在江湖的物品中可以看到采到的花朵。<br>
        </font><br>
        在这里种植的花是买不到的，把她送给自己心爱的人再好也不过！江湖还会定期举办种花大赛，到时您可以一显身手了!</b></font></p>
    </td>
  </tr>
  <tr> 
      <td> <p align="center"><font color="#FFFFFF"><a href="http://www.7758530.com"><font color="#FF0000">爱情江湖网制作</font></a> 
          <font color="#000000">授权--<%=Application("aqjh_chatroomname")%></font></font></p>
    </td>
  </tr>
  </tbody> 
</table>
</body>
</html>
