<html> 
<head>
<title>职业介绍所</title>
<link rel="stylesheet" href="../style.css" type="text/css">
</head>
<body oncontextmenu=self.event.returnValue=false leftmargin="0" topmargin="13" bgcolor="#000000">
<br>
<div align="center">
  <table border=1 align=center width=350 cellpadding="10" cellspacing="13">
    <tr bgcolor=005b00> 
      <td bgcolor="00A200"> 
        <table border="1" cellspacing="0" cellpadding="0" width="97" align="center" bordercolorlight=#00A200  bordercolordark=#339900>
          <tr> 
            <td height="81" valign="top"> 
              <div align="center"><font color="#000000"><b>欢迎光临职业转换所</b></font></div>
              <form method=POST action='cwork2.asp'>
                <table width="300" align="center" bordercolor="005b00">
                  <tr> 
                    <td> 
                  <tr> 
                    <td align=center><font color="#FFFF00">请选择您的职业</font>： 
                      <select name=jiu size=1>
                        <option value="cb">冰工</option>
                        <option value="ck">矿工</option>
                        <option value="du">渔夫</option>
                        <option value="mao">探险</option>
                        <option value="yao">郎中</option>
                        <option value="chu">厨师</option>
                      </select>
                    </td>
                  </tr>
                  <tr> 
                    <td  align=center> 
                      <input type=submit value=我选择好了 name="submit1">
                    </td>
                  </tr>
                  <tr> 
                    <td valign="top" height="8" > 
                      <div align="center">职业</div>
                    </td>
                  </tr>
                  <tr> 
                    <td valign="top" > 
                      <p><font color="#FFFF00">职业是您在江湖要的经济来源，选择不同的职业对您的工作会有不同的影响：</font></p>
                      <p align="center"><font color="#FFFFFF" size="2">转换职业需要10万职业介绍费请您想好！</font></p>
                    </td>
                  </tr>
                </table>
              </form>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</div>
</body>
</html>



