<html>
<head>
<link rel="stylesheet" href="../style.css">
<title>赌场</title>
</head>
<body oncontextmenu=self.event.returnValue=false background='../chatroom/bg1.gif'>
<p align="center">　</p>
<div align="center">
<center>
<table border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="100%" align="center">呵呵！欢迎大侠光临富贵赌坊，我们为你安排了各种赌的玩法。经常练功劳累的你
</center>
<p align="left">这里必然成为阁下的最佳之选！记住十赌九诈，小心为妙哦！————赌场门为卫</p>
</td>
</tr>
</table>
</div>
<p align="center">
<br>
<table border="0" width="50%" align=center cellspacing="0" cellpadding="0">
<tr>
<td align="center">赛马场</td>
<td align="center"><a href='#' onclick="javascript:horsewin=window.open('horse.asp','horse','left=0,top=40,status=yes,scrollbars=yes,resizable=yes');horsewin.resizeTo(screen.availWidth,screen.availHeight-80);" onmouseover="window.status='开始赌马';return true;" onmouseout="window.status='';return true;" title="开始赌马">开始游戏</a></td>
</tr>
<tr>
<td align="center">六合彩</td>
<td align="center"><a href="lottery.asp">开始游戏</a></td>
</tr>
<tr>
<td align="center">21&nbsp; 点</td>
<td align="center"><a href="21point.asp">开始游戏</a></td>
</tr>
<tr>
<td align="center">赌骰子</td>
<td align="center"><a href="dice.asp">开始游戏</a></td>
</tr>
<tr>
<td align="center">　</td>
<td align="center">　</td>
</tr>
</table>


<p align="center">　</p>
<p align="center">　<div id="Layer1" style="z-index: 1; width: 44; position: absolute; height: 48; left: 357; top: 216">
<img border="0" src="../image/bank.gif" width="29" height="27">
</div>

<div id="Layer2" style="z-index: 2; left: 184; width: 118; position: absolute; top: 218; height: 66">
<img border="0" src="../image/8.gif" width="111" height="63">&nbsp;&nbsp;
</div>

</body>

</html>
