<html><head><title>武器装备铸造</title> <meta http-equiv="Content-Type" content="text/html; charset=gb2312"><script language="JavaScript"><!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);
// -->
</script> <style type="text/css"><!--
-->
</style>
<link rel="stylesheet" href="../../style.css" type="text/css">
</head><body bgcolor="#000000" text="#FFFFFF" topmargin="0" leftmargin="0">
<table width="648" border="0" height="461" background="images/back.jpg"> <tr>
    <td height="397" valign="top" align="center" width="642"> <b><font color="#FFFF00">可铸造武器装备列表</font></b><br>
      <div align="left">
        <table border="1" cellpadding="0" cellspacing="0" width="619" bordercolorlight="#000000" bordercolordark="#FFFFFF">
          <tr> 
            <td   align="center" width="83"><div align="center"><font color="#FFCC66"><b>名称</b></font></div></td>
            <td width="346"  ><div align="center"><font color="#FFCC66"><b>所需材料</b></font></div></td>
            <td width="182"><div align="center"><font color="#FFCC66"><b>使用条件</b></font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="83"> <div align="center">
              <a href="xl1.asp"><font color="#FFFFFF">英雄之剑</font></a></div></td>
            <td width="346"  > <div align="left"><font color="#00FFFF">冰水:20个 
              铁块：20个 倚天剑：10把 大鲨鱼：5条</font></div></td>
            <td width="182"> <div align="left"><font color="#FFFF00">20级以下使用 攻击+1000000</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="83"> <div align="center">
              <a href="xl2.asp"><font color="#FFFFFF">英雄之铠</font></a></div></td>
            <td width="346"  > <div align="left"><font color="#00FFFF">矿石:20个 
              铁块：20个 露甘香：10个 大草鱼：5条</font></div></td>
            <td width="182"> <div align="left"><font color="#FFFF00">20级以下使用 
              防御+2000000</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="83"> <div align="center">
              <a href="xl3.asp"><font color="#FFFFFF">天王之刃</font></a></div></td>
            <td width="346"  > <div align="left"><font color="#00FFFF">冰水:50个 
                铁块：50个 屠龙刀：20把 小鲤鱼:10条</font></div></td>
            <td width="182"> <div align="left"><font color="#FFFF00">40级以下使用 
              攻击+2000000</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="83"> <div align="center">
              <a href="xl4.asp"><font color="#FFFFFF">天王之铠</font></a></div></td>
            <td width="346"  > <div align="left"><font color="#00FFFF">矿石:50个 
              铁块：50个 雨泉罩：20个 大鲨鱼:10条</font></div></td>
            <td width="182"> <div align="left"><font color="#FFFF00">40级以下使用 
              防御+3000000</font></div></td>
          </tr>
          <tr> 
            <td   height="16" align="center" width="83"> <div align="center">
              <a href="xl5.asp"><font color="#FFFFFF">电光之剑</font></a></div></td>
            <td   height="16" width="346"> <div align="left">
              <font color="#00FFFF">冰水:70个 铁块：70个 月星魔刀：30把 大草鱼:20条</font></div></td>
            <td width="182"> <div align="left"><font color="#FFFF00">60级以下使用 
              攻击+3000000</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="83"> <div align="center">
              <a href="xl6.asp"><font color="#FFFFFF">电光之铠</font></a></div></td>
            <td width="346"  > <div align="left"><font color="#00FFFF">矿石:70个 
              铁块：70个 神铛：30个&nbsp; 大草鱼:20条</font></div></td>
            <td width="182"> <div align="left"><font color="#FFFF00">60级以下使用 
              防御+4000000</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="83"> <div align="center">
              <a href="xl7.asp"><font color="#FFFFFF">破坏之剑</font></a></div></td>
            <td width="346"  > <div align="left"><font color="#00FFFF">冰水:100个 
              铁块：100个 圣火令：50个 小鲤鱼:30条</font></div></td>
            <td width="182"> <div align="left"><font color="#FFFF00">80级以下使用 
              攻击+5000000</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="83"> <div align="center">
              <a href="xl8.asp"><font color="#FFFFFF">破坏之铠</font></a></div></td>
            <td width="346"  > <div align="left"><font color="#00FFFF">矿石:100个 
              铁块：100个 白玉老虎：50个&nbsp;大草鱼:30条</font></div></td>
            <td width="182"> <div align="left"><font color="#FFFF00">80级以下使用 
              防御+7000000</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="83"> <div align="center">
              <a href="xl9.asp"><font color="#FFFFFF">魔幻之剑</font></a></div></td>
            <td width="346"  > <div align="left"><font color="#00FFFF">冰水:100个 
              铁块：100个 大龙令：80个 小鲤鱼:50条</font></div></td>
            <td width="182"> <div align="left"><font color="#FFFF00">100级以下使用 
              攻击+10000000</font></div></td>
          </tr>
          <tr> 
            <td  align="center" width="83"> <div align="center">
              <a href="xl10.asp"><font color="#FFFFFF">魔幻之铠</font></a></div></td>
            <td width="346"  > <font color="#00FFFF">矿石:100个 铁块：100个 长灵剑：80个 
            大鲨鱼:50条</font></td>
            <td width="182"> <div align="left"><font color="#FFFF00">100级以下使用 
              防御+13000000</font></div></td>
          </tr>
          </table>      
      </div>      
      <div id="Layer1" style="position: absolute; width: 114; height: 90; z-index: 1; left: 99; top: 260"><img src="images/fire.gif" width="82" height="70"></div><div id="Layer2" style="position: absolute; width: 78; height: 53; z-index: 2; left: 194; top: 308"><table width="75%" border="0" height="27"> <tr> <td><img src="images/firejj.gif" width="70" height="13"></td></tr><tr> <td> <div align="right"><img src="images/huochai2.gif" width="26" height="22"></div></td></tr></table></div><div id="Layer3" style="position: absolute; width: 200; height: 115; z-index: 3; left: 200; top: 268"><table width="75%" border="0" height="27" cellspacing="00" cellpadding="0"> <tr><td> <div align="center"><img src="images/taobar2.gif" width="34" height="40"></div></td></tr><tr> <td> <div align="center"><img src="images/ping.gif" width="51" height="65"></div></td></tr></table></div>          
      </td>          
  </tr> </table>                 
<p>&nbsp;          
</p><div align="center"></div></body></html>