<%@ LANGUAGE=VBScript codepage ="936" %><%

sjjh_name=Session("sjjh_name")
sjjh_grade=Session("sjjh_grade")
sjjh_jhdj=Session("sjjh_jhdj")
if sjjh_name="" then Response.Redirect "../../error.asp?id=440"


%>
<html>
<head>
<title>E线江湖美容院♀wWw.51eline.com♀</title>
<meta content="text/html; charset=gb2312" http-equiv="Content-Type">
<meta content="zh-cn" http-equiv="Content-Language">
<meta content="Microsoft FrontPage 4.0" name="GENERATOR">
<meta content="FrontPage.Editor.Document" name="ProgId">
<style type="text/css">body         { font-family: 宋体; font-size: 9pt }
td           { font-family: 宋体; font-size: 9pt }
a:link       { text-decoration: underline }
a:hover      { text-decoration: none }
.words       { line-height: 15pt }
BODY {
scrollbar-face-color:#ffffff; 
scrollbar-shadow-color:#000000; 
scrollbar-highlight-color:#000000;
scrollbar-3dlight-color:#ffffff;
scrollbar-darkshadow-color:#ffffff;
scrollbar-track-color:#000000;
scrollbar-arrow-color:#000000;
}
</style>
</head>

<body bgcolor="#FFFFFF" topmargin="0" leftmargin="0">
<div align="center">
  <table width="778" border="0" cellspacing="0" cellpadding="0" height="68">
    <tr bgcolor="#000000" valign="top">
      <td valign="middle"><img src="../../images/mr1.gif" width="98" height="29"></td>
</tr>
</table>

</div>
<table border="0" cellpadding="0" cellspacing="0" align="center"
width="778">
<tbody>
<tr>
<td align="middle" height="139"><a href="#"
title="我要美容"
onClick="window.open('meiyong1.asp?my=<%=sjjh_name%>','youyi','scrollbars=yes,resizable=yes,width=180,height=50')"><img
border="0" src="../../images/mr3.jpg" width="120" height="120"></a></td>
<td align="middle" height="139"><a href="#"
title="我要美容"
onClick="window.open('meiyong1.asp?my=<%=sjjh_name%>','youyi','scrollbars=yes,resizable=yes,width=180,height=50')"><img
border="0" src="../../images/mr4.jpg" width="120" height="120"></a></td>
<td align="middle" height="139"><a href="#"
title="我要美容"
onClick="window.open('meiyong1.asp?my=<%=sjjh_name%>','youyi','scrollbars=yes,resizable=yes,width=180,height=50')"><img
border="0" src="../../images/mr5.jpg" width="120" height="120"></a></td>
<td align="middle" height="139"><a href="#"
title="我要美容"
onClick="window.open('meiyong1.asp?my=<%=sjjh_name%>','youyi','scrollbars=yes,resizable=yes,width=180,height=50')"><img
border="0" src="../../images/mr6.jpg" width="120" height="120"></a></td>
<td align="middle" rowspan="2"><img src="../../images/mr2.gif" width="121" height="298"></td>
</tr>
<tr>
<td align="middle" valign="top"><a
href="#" title="我要美容"
onClick="window.open('meiyong1.asp?my=<%=sjjh_name%>','youyi','scrollbars=yes,resizable=yes,width=180,height=50')"><img
border="0" src="../../images/mr7.jpg" width="120" height="120"></a></td>
<td align="middle" valign="top"><a
href="#" title="我要美容"
onClick="window.open('meiyong1.asp?my=<%=sjjh_name%>','youyi','scrollbars=yes,resizable=yes,width=180,height=50')"><img
border="0" src="../../images/mr8.jpg" width="120" height="120"></a></td>
<td align="middle" valign="top"><a
href="#" title="我要美容"
onClick="window.open('meiyong1.asp?my=<%=sjjh_name%>','youyi','scrollbars=yes,resizable=yes,width=180,height=50')"><img
border="0" src="../../images/mr9.jpg" width="120" height="120"></a></td>
<td align="middle" valign="top"><a
href="#" title="我要美容"
onClick="window.open('meiyong1.asp?my=<%=sjjh_name%>','youyi','scrollbars=yes,resizable=yes,width=180,height=50')"><img
border="0" src="../../images/mr10.jpg" width="120" height="120"></a></td>
</tr>
</tbody>
</table>
<div align="center">
<table width="778" border="0" cellspacing="0" cellpadding="0" height="68">
<tr bgcolor="#000000" align="right" valign="bottom">
<td><font color="#666666">-这里都是美容院的学徒，美容费最少10两银子，增加魅力多少看您的运气!-<br><br>
</font></td>
</tr>
</table>

</div>
</body>

</html>
<html></html>