<%@ LANGUAGE=VBScript codepage ="936" %><HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<link href="../dg/setup.css" rel=stylesheet type="text/css">
<title>河畔钓鱼♀wWw.51eline.com♀</title></HEAD>
<body oncontextmenu=self.event.returnValue=false bgcolor="#000000" text="#ffffff" background="../jhimg/bk_hc3w.gif">
<p align="center"><b><font color="#000000">想钓鱼先进入聊天室！</font></b></p>
<p align="center"><A HREF="d.asp"><font color="#0000FF">开始钓鱼</font></A></p>
<p align="center"><font color="#000000">注：每次钓鱼时间为2分钟即120秒，上钩后15秒不</font></p>
<p align="center"><font color="#000000">拉杆就会溜走掉鱼的成功的机率是10%，大家看见河里有</font></p>
<p align="center"><font color="#000000">动静了就用鼠标点动的地方，就有机会钓到鱼，每8分钟<br>
</font></p>
<p align="center"><font color="#000000">可以进行钓鱼一次，如果鱼跑了只有等下一次了。</font><font color="red">
</font></p>
</BODY>
</HTML>