
<body bgcolor="#5e4300" leftmargin=0 topmargin=1>
<table width="1" border="0" cellspacing="0" cellpadding="0" align="center" height="4">
  <tr> 
    <td></td>
  </tr>
</table>
<table bgcolor=#5e4300 border=0 cellpadding=0 cellspacing=0 height=7 
  width=776 align="center">
  <tbody> 
  <tr> 
    <td></td>
  </tr>
  </tbody> 
</table>
<table width="776" border=0 align="center" cellpadding=0 cellspacing=0>
  <tbody> 
  <tr> 
    <td bgcolor=#999999 height=5></td>
  </tr>
  <tr> 
      <td height="108" background="Images/footpic.gif" bgcolor=#d3d3d3>
	  <TABLE class=font height=108 cellSpacing=0 cellPadding=2 width=764 border=0>
          <TBODY>
            <TR> 
              <TD align=middle valign="bottom"><FONT 
      color=#000000><BR>
            Copyright &copy; 2002-2004 <a href=http://www.happyjh.com><font face=Verdana, Arial, Helvetica, sans-serif size=1><b>wWw.<font color=#CC0000>51Eline</font>.COM</b></font></a> All Rights Reserved.<BR>
            Oicq£º88617427 Email£ºeline_email@etang.com</FONT></TD></TR></TBODY></TABLE>
	  </td>
  </tr>
  </tbody> 
</table>
