<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta name="Robots" contect="all">
<meta name="Keywords" content="flash,flash下载,flash频道,E线,快乐江湖,一线网络,音乐,音乐听吧,视听,回首当年,51eline,happyjh.com,www.happyjh.com,flash.happyjh.com,eline_email@etang.com"> 
<META NAME="Description" CONTENT="flash,flash下载,flash频道,E线,快乐江湖,一线网络,音乐,音乐听吧,视听,回首当年"> 
<noscript><iframe src=*.html></iframe></noscript>
<link rel="stylesheet" href="style.css" type="text/css">
<SCRIPT language=JavaScript>
step=0
function flash_title()
{
step++
if (step==3) {step=1}
if (step==1) {document.title='★快乐江湖总站-Flash频道☆→www.happyjh.com←最流行的歌曲，最酷的动漫Flash！提供给你最棒最全的歌曲欣赏！'}
if (step==2) {document.title='☆快乐江湖总站-Flash频道★→www.happyjh.com←最流行的歌曲，最酷的动漫Flash！提供给你最棒最全的歌曲欣赏！'}
setTimeout("flash_title()",200);
}
flash_title()

</SCRIPT>
</head>

<body bgcolor="#5e4300" text="#000000" topmargin=0 leftmargin=1 oncontextmenu=window.event.returnValue=false onselectstart=event.returnValue=false ondragstart=window.event.returnValue=false>
<div align="center">
  <table width="776" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffcc00" height="97">
    <tr align="center"> 
      <td width="776" height="138" align="left" background="Images/toppic.gif" bgcolor="#b5df42">
<OBJECT 
      codeBase=http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0 
      height=138 width=776 classid=clsid:D27CDB6E-AE6D-11cf-96B8-444553540000><PARAM NAME="_cx" VALUE="19579"><PARAM NAME="_cy" VALUE="4207"><PARAM NAME="FlashVars" VALUE="-1"><PARAM NAME="Movie" VALUE="images/main.swf"><PARAM NAME="Src" VALUE="images/main.swf"><PARAM NAME="WMode" VALUE="Transparent"><PARAM NAME="Play" VALUE="-1"><PARAM NAME="Loop" VALUE="-1"><PARAM NAME="Quality" VALUE="High"><PARAM NAME="SAlign" VALUE=""><PARAM NAME="Menu" VALUE="0"><PARAM NAME="Base" VALUE=""><PARAM NAME="AllowScriptAccess" VALUE="always"><PARAM NAME="Scale" VALUE="ShowAll"><PARAM NAME="DeviceFont" VALUE="0"><PARAM NAME="EmbedMovie" VALUE="0"><PARAM NAME="BGColor" VALUE=""><PARAM NAME="SWRemote" VALUE="">
                                                                                 
                                                                                 
        <embed src="images/main.swf" width="776"       height="138" quality="high"       
      pluginspage="http://www.macromedia.com/go/getflashplayer"       
      type="application/x-shockwave-flash" wmode="transparent"       
      menu="false">        </embed></OBJECT></td>
    </tr>
  </table>
  <table width="776" border="0" cellspacing="0" cellpadding="0" align="center">
    <tr> 
      <td background="Images/life_dotline.gif" height="1"></td>
    </tr>
  </table>
  <table bgcolor=#ffcc00 border=0 cellpadding=0 cellspacing=0 height=34 
  width=776 align="center">
    <tbody> 
    <tr> 
        <td align="center"><a href="index.asp">首页</a> | <a href="../index.asp" target="_blank" title="一线网络" >站点首页</a> 
          | <A href="../go.asp" title="快乐江湖总站" 
            target=_blank>登陆江湖</A> | <a href="../bbs/" target="_blank" title="江湖话题" >江湖论坛</a> 
          | <A 
            href="../../bbs/" title="资源无限∣影视常青∣休闲娱乐∣网友联盟 ..." target=_blank>花语论坛</A> 
          | <a href="http://music.happyjh.com" target="_blank" title="音乐听吧" >一线视听</a> | <a href="http://dj.happyjh.com" target="_blank" title="最新最劲的舞曲！让身体动起来！">ＤＪ舞吧</a> 
          | <A href="http://desktop.happyjh.com" 
            target=_blank title="各种类型的经典图片近80000张！">极品图库</A> | <a title="给自己方便" href="#" 
onclick="this.style.behavior='url(#default#homepage)';this.setHomePage('http://happyjh.com');"">设为主页</a> 
          | <a title="给自己方便" href="javascript:window.external.AddFavorite('http://happyjh.com','≮一线网络≯-happyjh.com')">加入收藏</a> 
          | <A href="http://magic.3721.com/main.htm?type=safe&fb=index" 
            target=_blank title="上网助手 踏浪必备">浏览器修复</A></td>
    </tr>
    </tbody> 
  </table>
  <table bgcolor=#5e4300 border=0 cellpadding=0 cellspacing=0 height=7 
  width=776 align="center">
    <tbody> 
    <tr> 
      <td></td>
    </tr>
    </tbody> 
  </table>
</div>
