<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<link href="../dg/setup.css" rel=stylesheet type="text/css">
<title>挖掘宝藏♀wWw.happyjh.com♀</title></HEAD>
<body oncontextmenu=self.event.returnValue=false bgcolor="#000000" text="#ffffff">
<%Session("diaoyu")=true%>
<p align="center"><b><font color="#000000">想挖宝先进入聊天室！</font></b></p>
<p align="center">&nbsp;</p>
<p align="center"><A HREF="wa.asp"><font color="#FFFF00" size="2">开始挖宝藏</font></A></p>
<p align="center"><font color="#FFFFFF" size="2">每挖一次宝藏都会用去50至90不等的内力，挖到的话,被抢走<br>
  的机会是10%，只要看到你的手上抱有黄金就点击下去.不过,<br>
  体力1000以下的大侠是不能探宝的挖宝藏一定要注意时机,因<br>
  为这一带挖的人很多,一不小心就会被抢走,有时候遇到强盗<br>
  还会杀死你的......</font></p>

<p align="center">&nbsp;</p>
<p align="center">&nbsp;</p>
<p align="center"><font size="2" color="#000000">快乐江湖版权所有 2003-2004</font></p>
</BODY>
</HTML>