<%
Response.CacheControl="no-cache"
Response.AddHeader "pragma","no-cache"
Response.Expires=-1
bgcolor=Application("Ba_jxqy_backgroundcolor")
bgimage=Application("Ba_jxqy_backgroundimage")
username=session("Ba_jxqy_username")
mycorp=session("Ba_jxqy_usercorp")
mygrade=session("Ba_jxqy_usergrade")
if username="" then Response.redirect "../error.asp?id=016"
msg="<head><link rel='stylesheet' href='../chatroom/style1.css'></head><body oncontextmenu=self.event.returnValue=false background='"&bgimage&"' bgcolor='"&bgcolor&"'><table width=100% align=center border=0><tr><td><a href='../street/prison.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='监狱';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"监狱"&chr(34)&">监&nbsp;&nbsp;&nbsp;&nbsp;狱</a></td></tr><tr><td><a href='herostele.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='先烈祠';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"先烈祠"&chr(34)&">先&nbsp;烈&nbsp;祠</a></td></tr><tr><td><a href='onlinelist.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='情缘在线';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"情缘在线"&chr(34)&">情缘在线</a></td></tr><tr><td><a href='modcorp1.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='门派管理';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"门派管理"&chr(34)&">门派管理</a></td></tr><tr><td><a href='modatt1.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='武功设置';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"武功设置"&chr(34)&">武功设置</a></td></tr><tr><td><a href='modmill1.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='打工管理';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"打工管理"&chr(34)&">打工管理</a></td></tr><tr><td><a href='modarm1.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='武器管理';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"武器管理"&chr(34)&">武器管理</a></td></tr><tr><td><a href='modcur1.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='药品管理';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"药品管理"&chr(34)&">药品管理</a></td></tr>"
if mycorp="官府" and mygrade>=Application("Ba_jxqy_exaltgraderight") then msg=msg&"<tr><td><a href='showgov.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='人员管理';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"人员管理"&chr(34)&">人员管理</a></td></tr>"
if mycorp="官府" and mygrade=Application("Ba_jxqy_allright") then msg=msg&"<tr><td><a href='showballot.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='投票系统';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"投票系统"&chr(34)&">投票系统</a></td></tr><tr><td><a href='showsystem.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='系统设置';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"系统设置"&chr(34)&">系统设置</a></td></tr><tr><td><a href='selectuser.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='用户资料';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"用户资料"&chr(34)&">用户资料</a></td></tr><tr><td><a href='upboard1.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='论坛管理';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"论坛管理"&chr(34)&">论坛管理</a></td></tr><tr><td><a href='seedel.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='已删贴';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"已删贴"&chr(34)&">已&nbsp;删&nbsp;贴</a></td></tr><tr><td><a href='addstock.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='增发新股';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"增发新股"&chr(34)&">增发新股</a></td></tr><tr><td><a href='allocate.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='股票分红';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"股票分红"&chr(34)&">股票分红</a></td></tr><tr><td><a href='showfell.asp' target='resultfrm'>会员管理</a></td></tr><tr><td><a href='showcard.asp' target='resultfrm'>道具管理</a></td></tr><tr><td><a href='showmid.asp' target='resultfrm'>歌曲管理</a></td></tr><tr><td><a href='showimg.asp' target='resultfrm'>贴图管理</a></td></tr><tr><td><a href='showmap.asp' target='resultfrm'>地图管理</a></td></tr><tr><td><a href='showbio.asp' target='resultfrm'>怪物管理</a></td></tr>"
msg=msg&"<tr><td><a href='addcorp.asp' target='resultfrm' onmouseover="&chr(34)&"window.status='自立门户';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" >自立门户</a></td></tr><tr><td>&nbsp;</td></tr><tr><td><a href='javascript:top.window.close();' onmouseover="&chr(34)&"window.status='关闭';return true;"&chr(34)&" onmouseout="&chr(34)&"window.status='';return true;"&chr(34)&" title="&chr(34)&"关闭"&chr(34)&">关&nbsp;&nbsp;&nbsp;&nbsp;闭</a></td></tr></table></body>"
Response.Write msg
%>
