<html><head><title>练药</title> <meta http-equiv="Content-Type" content="text/html; charset=gb2312"><script language="JavaScript"><!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);
// -->
</script> <style type="text/css"><!--
-->
</style>
<link rel="stylesheet" href="../../style.css" type="text/css">
</head><body bgcolor="#000000" text="#FFFFFF" topmargin="0" leftmargin="0"><table width="640" border="0" height="461" background="images/back.jpg"> <tr>
    <td height="397" valign="top" align="center"> <b><font color="#FFFF00">可铸造的武器装备列表</font></b><br>
      <div align="left">
        <table border="1" cellpadding="0" cellspacing="0" width="415" bordercolorlight="#000000" bordercolordark="#FFFFFF">
          <tr> 
            <td   align="center" width="103"><div align="center"><font color="#FFCC66"><b>名称</b></font></div></td>
            <td width="205"  ><div align="center"><font color="#FFCC66"><b>所需材料</b></font></div></td>
            <td width="99"><div align="center"><b><font color="#FFCC66">功效</font></b></div></td>
          </tr>
          <tr> 
            <td   align="center" width="103"> <div align="center"><a href="xl1.asp" target="cz"><font color="#FFFF00">大力丸</font></a></div></td>
            <td width="205"  > <div align="center"><font color="#00FFFF">冰水:5个</font></div></td>
            <td width="99"> <div align="center"><font color="#FFFFFF">攻击:+100</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="103"> <div align="center"><a href="xl2.asp" target="cz"><font color="#FFFF00">归命丸</font></a></div></td>
            <td width="205"  > <div align="center"><font color="#00FFFF">冰水:5个</font></div></td>
            <td width="99"> <div align="center"><font color="#FFFFFF">防御:+100</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="103"> <div align="center"><a href="xl3.asp" target="cz"><font color="#FFFF00">九花玉露丸</font></a></div></td>
            <td width="205"  > <div align="center"><font color="#00FFFF">冰水:15个 
                小鲤鱼:2条</font></div></td>
            <td width="99"> <div align="center"><font color="#FFFFFF">内力:+1000000</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="103"> <div align="center"><a href="xl4.asp" target="cz"><font color="#FFFF00">三花聚顶</font></a></div></td>
            <td width="205"  > <div align="center"><font color="#00FFFF">冰水:10个 
                大草鱼:4条</font></div></td>
            <td width="99"> <div align="center"><font color="#FFFFFF">体力:+6000000</font></div></td>
          </tr>
          <tr> 
            <td   height="16" align="center" width="103"> <div align="center"><a href="xl5.asp" target="cz"><font color="#FFFF00">豹胎易筋丸</font></a></div></td>
            <td   height="16" width="205"> <div align="center"><font size="-1" color="#00FFFF">冰水:8个 
                矿石:8个 大鲨鱼:3&nbsp;</font></div></td>
            <td width="99"> <div align="center"><font color="#FFFFFF">体力:+5000000</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="103"> <div align="center"><a href="xl6.asp" target="cz"><font color="#FFFF00">清凉油</font></a></div></td>
            <td width="205"  > <div align="center"><font color="#00FFFF">矿石:5个</font></div></td>
            <td width="99"> <div align="center"><font color="#FFFFFF">精力:+1000</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="103"> <div align="center"><a href="xl7.asp" target="cz"><font color="#FFFF00">夺命金丹</font></a></div></td>
            <td width="205"  > <div align="center"><font color="#00FFFF">矿石:10个 
                小鲤鱼:5条</font></div></td>
            <td width="99"> <div align="center"><font color="#FFFFFF">神秘暗器</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="103"> <div align="center"><a href="xl8.asp" target="cz"><font color="#FFFF00">易容药</font></a></div></td>
            <td width="205"  > <div align="center"><font color="#00FFFF">冰水:3个 
                矿石:3个</font></div></td>
            <td width="99"> <div align="center"><font color="#FFFFFF">魅力:+1000</font></div></td>
          </tr>
          <tr> 
            <td   align="center" width="103"> <div align="center"><a href="xl9.asp" target="cz"><font color="#FFFF00">大还丹</font></a></div></td>
            <td width="205"  > <div align="center"><font color="#00FFFF">冰水：8个 
                矿石:8个 大草鱼:1条</font></div></td>
            <td width="99"> <div align="center"><font color="#FFFFFF">资质:+10000</font></div></td>
          </tr>
          <tr> 
            <td  align="center" width="103"> <div align="center"><a href="xl10.asp" target="cz"><font color="#FFFF00">九转还魂丹</font></a></div></td>
            <td width="205"  > <font color="#00FFFF">冰水:30个 矿石:30个 大草鱼30条&nbsp;</font></td>
            <td width="99"> <div align="center"><font color="#FFFFFF">神秘宝物</font></div></td>
          </tr>
          <tr> 
            <td   align="center"> <div align="center"><a href="xl11.asp" target="cz"><font color="#FFFF00">五香肉</font></a></div></td>
            <td  > <div align="center"><font color="#00FFFF">冰水:5个 矿石:5个&nbsp;</font></div></td>
            <td> <div align="center"><font color="#FFFFFF">攻击:+200</font></div></td>
          </tr>
          </table>      
      </div>      
      <div id="Layer1" style="position: absolute; width: 114; height: 90; z-index: 1; left: 99; top: 260"><img src="images/fire.gif" width="82" height="70"></div><div id="Layer2" style="position: absolute; width: 78; height: 53; z-index: 2; left: 194; top: 308"><table width="75%" border="0" height="27"> <tr> <td><img src="images/firejj.gif" width="70" height="13"></td></tr><tr> <td> <div align="right"><img src="images/huochai2.gif" width="26" height="22"></div></td></tr></table></div><div id="Layer3" style="position: absolute; width: 200; height: 115; z-index: 3; left: 200; top: 268"><table width="75%" border="0" height="27" cellspacing="00" cellpadding="0"> <tr><td> <div align="center"><img src="images/taobar2.gif" width="34" height="40"></div></td></tr><tr> <td> <div align="center"><img src="images/ping.gif" width="51" height="65"></div></td></tr></table></div>          
      </td>          
  </tr> </table>                 
<p>&nbsp;          
</p><div align="center"></div></body></html>