<html>

<head>
<style></style>
<link rel="stylesheet" href="../style4.css" type="text/css">

</head>

<body bgcolor="#000000">
<p align=center style='font-size:20;color:yellow'><img border="0" src="bf.gif"><p align=center style='font-size:20;color:yellow'><img border="0" src="1.jpg">
<table width="56%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr> 
    <td colspan="3" height="39"><font color="#FFFF00"><font size="2">金碧辉煌的相国寺，果然气派不凡，不愧为皇家寺院</font></font></td>
  </tr>
  <tr> 
    <td width="27%" height="14"> 
      <div align="center"><font color="#FFFF00" size="2">方式</font></div>
    </td>
    <td width="33%" height="14"> 
      <div align="center"><font color="#FFFF00" size="2">道德</font></div>
    </td>
    <td width="40%" height="14"> 
      <div align="center"><font color="#FFFF00" size="2">花费</font></div>
    </td>
  </tr>
  <tr> 
    <td width="27%" height="16"> 
      <div align="center"><font color="#FFFF00" size="2">拜佛</font></div>
    </td>
    <td width="33%" height="16"> 
      <div align="center"><font size="2" color="#FFFF00">40</font></div>
    </td>
    <td width="40%" height="16">
      <div align="center"><font color="#FFFF00">2000</font></div>
    </td>
  </tr>
  <tr> 
    <td width="27%"> 
      <div align="center"><font color="#FFFF00" size="2">烧香</font></div>
    </td>
    <td width="33%">
      <div align="center"><font color="#FFFF00">60</font></div>
    </td>
    <td width="40%">
      <div align="center"><font color="#FFFF00">3000</font></div>
    </td>
  </tr>
  <tr> 
    <td width="27%"> 
      <div align="center"><font color="#FFFF00" size="2">还愿</font></div>
    </td>
    <td width="33%">
      <div align="center"><font color="#FFFF00">80</font></div>
    </td>
    <td width="40%">
      <div align="center"><font color="#FFFF00">4000</font></div>
    </td>
  </tr>
  <tr> 
    <td width="27%"> 
      <div align="center"><font color="#FFFF00" size="2">捐赠</font></div>
    </td>
    <td width="33%">
      <div align="center"><font color="#FFFF00">100</font></div>
    </td>
    <td width="40%">
      <div align="center"><font color="#FFFF00">5000</font></div>
    </td>
  </tr>
</table>
<table border=1 bgcolor="#00A200" align=center width=350 cellpadding="10" cellspacing="13">
<tr><td bgcolor=#005b00>
<table>
<tr><td>
<form method=POST action='do.asp'>
<tr>
          <td align=center>请问，施主来毕寺是想： 
            <select name=jiu size=1>
              <option value="lao">拜佛 </option>
              <option value="wu">烧香 </option>
              <option value="du">还愿 </option>
              <option value="mao">捐赠 </option>
            </select>
</td><td colspan=2 align=center><input type=submit value=确定>
<tr><td colspan=2 style='font-size:9pt'><hr>
            佛主说的好：“放下屠刀，立地成佛”，居然施主能来这里，就说明你还有一份仁慈之心！不过香火钱不能少。 <br>
            </td>
        </tr>
</form>
</table>
</table>
</body>
</html>



