<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>♀wWw.happyjh.com♀</title>
<base target="main">
</head>

<body topmargin="0" leftmargin="0" oncontextmenu=self.event.returnValue=false bgcolor="#CCCCCC">
<table border="0" cellpadding="0" cellspacing="0" width="253">
  <tr>
   <td><img src="img/shim.gif" width="11" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="30" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="6" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="31" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="7" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="6" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="1" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="3" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="10" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="34" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="10" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="5" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="7" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="5" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="38" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="6" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="23" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="10" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="10" height="1" border="0"></td>
   <td><img src="img/shim.gif" width="1" height="1" border="0"></td>
  </tr>

  <tr valign="top">
    <td colspan="4"><a href="zb.asp"><img name="zb_r01_c01" src="img/zb_r01_c01.jpg" width="118" height="24" border="0"></a></td>
    <td colspan="2">&nbsp;</td>
    <td colspan="5"><a href="../ZHUANGT.ASP"><img name="zb_r01_c13" src="img/zb_r01_c13.jpg" width="118" height="24" border="0"></a></td>
   <td colspan="2"><a href="javascript:window.close()"><img name="zb_r01_c18" src="img/zb_r01_c18.jpg" width="20" height="24" border="0"></a></td>
   <td><img src="img/shim.gif" width="1" height="24" border="0"></td>
  </tr>

</table>

</body>

</html>
