
<html>
<head>
<title>出家还俗</title>
<link rel="stylesheet" href="../style.css">
<script language=javascript>
<!--
function panbang(){
	if(confirm('你确定要出家吗？')){
	parent.location.href='huansu2.asp';
	}
}
function panbanga(){
	if(confirm('你确定要还俗吗？')){
	parent.location.href='huansu1.asp';
	}
}
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
</head>
<body bgcolor=#000000 text="#FFFFFF" oncontextmenu=self.event.returnValue=false background="1.jpg">
<p align="center"><b><font size="4" color="#FFFF00">五台山上</font></b></p>
<div align="center">
  <center>
<table width="397" border="1" cellspacing="0" cellpadding="0" height="1" bordercolor="#FFFF00" style="border-collapse: collapse">
<tr>
<td height="66" width="198" bgcolor="#CCCCCC">
<font color="#000000">
如果你真底看破红尘，已经没有要爱的人了，那好吧，就让我一休大师为你削发剃度，从今后，你就是五台山的一名和尚了，你要遵守寺规，不能在外面打架，外面的人也不能打你，好了</font><a href="huansu2.asp"><font color="#0000FF">我们开始吧</font></a>......
</td>
<td height="66" width="199" bgcolor="#CCCCCC">
<p align="center">
<img border="0" src="../image/E8.jpg"></td>
</tr>
<tr>
<td height="67" width="198" bgcolor="#CCCCCC">
<font color="#FF0000">&nbsp; 别忘了出家和还俗都要带<b>1000000</b>两的，出家后不能攻击他人，他人也不能攻击你，出家后本来的门派就没有了，如果你是掌门的都没有了。而你还俗也是不能恢复以前的门派和掌门身份的，三思而后行啊，祝福你！</font></td>
<td height="67" width="199" bgcolor="#CCCCCC">
<font color="#000000">如果你真的爱上了一个人的话，就算了吧，大家并不是不给你机会, 
请带上1000000两来此还俗，不过还俗后还要减少300点的道德 如果你考虑好了</font>，<a href="huansu1.asp"><font color="#0000FF">请进来</font></a><font color="#0000FF">.</font>.....  
<br>  
</td>  
</tr>  
</table> 
  </center>
</div>
<div id="Layer1" style="z-index: 1; width: 128; position: absolute; height: 112; left: 58; top: 168">
&nbsp;</div>
</body>
</html>