<html>

<head>
<title>转换市场♀wWw.51eline.com♀</title>
</head>

<body leftmargin="0" topmargin="0" bgcolor="#CCCCCC" background="../chat/back.jpg">
<div align="center"><b><font color="#008080">欢迎大侠<img border="0" src="../chat/img/31.gif">光临转换市场！</font></b></div>
<div align="center">　</div>
<div align="center"><img border="0" src="../chat/img/05s.jpg"><img border="0" src="../chat/img/07s.jpg"><img border="0" src="../chat/img/17s.jpg"><img border="0" src="../chat/img/1414.jpg"></div>
<br>
        <table width="568" align="center" height="10">
          <tr>   
            <td valign="top" height="36" width="132" >   
              <a href="yule.asp"><font color="#008080">金币转换</font></a> 
            </td> 
            <td valign="top" height="36" width="97" >   
              <a href="yule2.asp"><font color="#0000FF">银两转换</font></a> 
            </td> 
            <td valign="top" height="36" width="109" >   
              <a href="yule3.asp"><font color="#FF0000">体力转换</font></a> 
            </td> 
            <td valign="top" height="36" width="117" >   
              <a href="../hyzh/zhuan.asp"><font color="#800000">会员转换</font></a> 
            </td> 
            <td valign="top" height="36" width="119" >   
              <a href="yule4.asp"><font color="#FB7D59">武功转换</font></a> 
            </td> 
            <td valign="top" height="36" width="114" >   
              <a href="yule5.asp"><font color="#000000">法力转换</font></a> 
            </td> 
            <td valign="top" height="36" width="110" >   
              <a href="yule6.asp"><font color="#FF00FF">银币转换</font></a> 
            </td> 
          </tr> 
          <tr>   
            <td valign="top" height="238" width="132" >   
              <font color="#008080">   
              金币转换金卡，10个金币=1元金卡。</font> 
            </td> 
            <td valign="top" height="238" width="97" >   
              <font color="#0000FF">   
              金币转换银两，1个金币=1000000两。</font> 
            </td> 
            <td valign="top" height="238" width="109" >   
              <font color="#FF0000">   
              金币转换体力，1个金币=35000点体力。</font> 
            </td> 
            <td valign="top" height="238" width="117" >   
              <font color="#800000">   
              金币、金卡、银币转换会员。</font> 
            </td> 
            <td valign="top" height="238" width="119" >   
              <p><font color="#FB7D59">金币转换武功，1个金币=1500点武功</font>。</p> 
            </td> 
            <td valign="top" height="238" width="114" >   
              <p>金币转换武功，1个金币=5000点法力。</p> 
            </td> 
            <td valign="top" height="238" width="110" >   
              <p><font color="#FF00FF">金币转换银币，1个金币=10个银币。</font></p> 
            </td> 
          </tr> 
        </table> 
<div align="center"><b><font color="#0000FF"><font color="red"><%=Application("sjjh_chatroomname")%></font>修改制作</font></b> 
</div> 
</body> 
</html>