<html>
<head>
<title>卖铁</title>
<LINK href="../../../style2.css" rel=stylesheet>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
</head>
<body bgcolor="#000000" text="#FFFFFF" topmargin="0" link="#0000FF" vlink="#0000FF" alink="#0000FF" leftmargin="0">
<table width="453" border="1" cellpadding="0" cellspacing="0" align="center">
  <tr> 
    <td height="26" width="80" nowrap> 
      <p align="center"><a href="Savemine.asp" target="cz1">
      <span style="font-size: 9pt">储存铁块</span></td>
    <td height="26" width="367"><span style="font-size: 9pt">保存之后可以用来铸造超级装备，攻击和防御都很高哦！</span></td>
  </tr>
  <tr> 
    <td height="26" width="80" nowrap> 
      <div align="center"><font style="font-size: 9pt"></a><a href="maitie.asp" target="cz1">出售铁块</a></font></div>
    </td>
    <td height="26" width="367"><font style="font-size: 9pt"><a href="maitie.asp" target="cz1">现在一块铁块价钱50000两，选择卖出可以将铁块转换成银两！</a></font></td>
  </tr>
</table>
</body>
</html>