<head><title>和尚修炼</title><link rel=stylesheet href='../../style.css'></head>
<body background='../../chatroom/bg1.gif'>
<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td width="65%">
      <p align="center">阿弥陀佛，我是虚竹和尚，作为一个出家人有出家人的规矩。在</p>
      <p align="center">江湖中是不允许打架的。我们出家人都是为了远离俗世，得道成</p>
      <p align="center">佛，但是能达者，不过寥寥无几也。记住：一心向佛，普渡众生</p>
      <p align="center">，方能成为得到高僧，能吃苦中苦，方为人上人，好知为知了！
      <p align="center"><a href="hs2.asp"><font color="#0000FF">进入禅房修炼</font></a></td>
    <td width="35%"><img border="0" src="xz.gif"></td>
  </tr>
</table>
