<%
Ba_hostname=Application("Ba_jxqy_hostname")
Ba_homepage="http://www.mxcz.org"
Ba_bgcolor=Application("Ba_jxqy_backgroundcolor")
Ba_bgimage=Application("Ba_jxqy_backgroundimage")
Ba_pagename=Application("Ba_jxqy_userright")					
Ba_hotbbsnum=20
Ba_pagesize=20
Ba_copyright="<P align=center>Powered by <A href='http://www.mxcz.org/'>梦想成真工作室</A> &copy; All Rights Reserved</P>"
%>
<Script Language="JScript" Runat=Server>
$UBBCode = 0;              
$html    = 0;              
$Smilies = 0;            
function Autolink(temp){temp=patch(temp);temp=Smilies(temp);if (!$UBBCode){temp = temp.replace(/(^|\s)(http|https|ftp)(:\/\/[^\";,<>]+)/ig, "<a href=\"$2$3\" target=_blank>$2$3</a>");temp = temp.replace(/([^\/]])(www\.[^\";,<>]+)/ig, "<a href=\"http:\/\/$2\" target=_blank>$2</a>");temp = temp.replace(/(^|\s)(www\.[^\";,<>&]+)/ig, "<a href=\"http:\/\/$2\" target=_blank>$2</a>");temp = temp.replace(/(\[URL\])(http|https|ftp)(:\/\/\S+)(\[\/URL\])/ig, "<A HREF=\"$2$3\" TARGET=_blank>$2$3</A>");temp = temp.replace(/(\[URL\])(\S+)(\[\/URL\])/ig, "<A HREF=\"http:\/\/$2\" TARGET=_blank>$2</A>");temp = temp.replace(/(\[URL=)(http|https|ftp)(:\/\/\S+)(\])(\S+)(\[\/URL\])/ig, "<A HREF=\"$2$3\" TARGET=_blank>$5</A>");temp = temp.replace(/(\[email=)(\S+)(\])(.+)(\[\/email\])/ig, "<A HREF=\"http:\/\/$2\" TARGET=_blank>$4</A>");temp = temp.replace(/(\[email\])(\S+)(\[\/email])/ig,"<a href=\"mailto:$2\">$2</a>");temp = temp.replace(/(\[URL=)(\S+)(\])(.+)(\[\/URL\])/ig, "<a href=\"http:\/\/$2\" TARGET=_blank>$4</A>");temp = temp.replace(/(\[img\])(file:|javascript:|vbscript:|script:)(\S+)(\[\/img\])/ig, "<font color=ff0000>怀疑危险的图片链接:$2$3</font>");temp = temp.replace(/(\[img\])(\S+)(\[\/img\])/ig, "<img border=0 src=\"$2\" alt=\"$2\">");temp = temp.replace(/(\[code\])(.+)(\[\/code\])/ig, "<BR><BLOCKQUOTE><strong>Code</strong>:<HR Size=1>$2<HR SIZE=1><\/BLOCKQUOTE>");temp = temp.replace(/(\[QUOTE\])(.+)(\[\/QUOTE\])/ig, "<BR><BLOCKQUOTE><strong>引用</strong>:<HR Size=1>$2<HR SIZE=1><\/BLOCKQUOTE>");temp = temp.replace(/(\[COLOR=)(\S+)(\])(.+)(\[\/COLOR\])/ig, "<FONT COLOR=\"$2\">$4<\/FONT>");temp = temp.replace(/(\[list\])(.+)(\[\/list\])/ig, "<UL TYPE=SQUARE>$2<\/UL>");temp = temp.replace(/(\[list=A\])(.+)(\[\/list\])/ig, "<ol type=A>$2<\/ol>");temp = temp.replace(/(\[list=1\])(.+)(\[\/list\])/ig, "<ol type=1>$2<\/ol>");temp = temp.replace(/(\[center\])(.+)(\[\/center\])/ig, "<CENTER>$2<\/CENTER>");temp = temp.replace(/(\[fly\])(.+)(\[\/fly\])/ig, "<marquee>$2<\/marquee>");temp = temp.replace(/(\[i\])(.+)(\[\/i\])/ig, "<I>$2<\/I>");temp = temp.replace(/(\[b\])(.+)(\[\/b\])/ig, "<B>$2<\/B>");temp = temp.replace(/(\[u\])(.+)(\[\/u\])/ig, "<U>$2<\/U>");temp = temp.replace(/(\[\*\])/ig, "<LI>");temp = temp.replace(/(\[font )(\S+)(\ )(\S+)(\ )(\S+)(\])(.+)(\[\/font\])/ig,"<font $2 $4 $6>$8</font>");temp = temp.replace(/(\[font )(\S+)(\ )(\S+)(\])(.+)(\[\/font\])/ig,"<font $2 $4>$6</font>");temp = temp.replace(/(\[font )(\S+)(\])(.+)(\[\/font\])/ig,"<font $2>$4</font>");}return (temp);}
function Smilies(temp){if (!$Smilies){temp = temp.replace(/\:\)/ig, "<img border=0 src=\"..\/images\/smile.gif\">");temp = temp.replace(/\:\(/ig, "<img border=0 src=\"..\/images\/frown.gif\">");temp = temp.replace(/\:D/g, "<img border=0 src=\"..\/images\/biggrin.gif\">");temp = temp.replace(/\&lt\;\)/ig, "\&lt\;\ )");temp = temp.replace(/\&gt\;\)/ig, "\&gt\;\ )");temp = temp.replace(/\;\)/ig, "<img border=0 src=\"..\/images\/wink.gif\">");temp = temp.replace(/\:o/g, "<img border=0 src=\"..\/images\/redface.gif\">");temp = temp.replace(/\:p/g, "<img border=0 src=\"..\/images\/tongue.gif\">");temp = temp.replace(/\:cool:/ig, "<img border=0 src=\"..\/images\/cool.gif\">");temp = temp.replace(/\:rolleyes:/g, "<img border=0 src=\"..\/images\/rolleyes.gif\">");temp = temp.replace(/\:mad:/g, "<img border=0 src=\"..\/images\/mad.gif\">");temp = temp.replace(/\:eek:/ig, "<img border=0 src=\"..\/images\/eek.gif\">");temp = temp.replace(/\:confused:/ig, "<img border=0 src=\"..\/images\/confused.gif\">");}return (temp);}
function patch(temp){if (!$html){temp = temp.replace(/</ig, "&lt;");temp = temp.replace(/>/ig, "&gt;");temp = temp.replace(/\r\n/ig, "<BR> ");}temp = temp.replace(/\n\r\n/ig, "<P>");temp = temp.replace(/\n/ig, "<BR>");temp = temp.replace(/\r/ig, "");return (temp);}
function showcname(bid,cname,bdinfo){temp="<a href='showboard.asp?bid="+bid+"' onmouseover=\"window.status='"+bdinfo+"';return true;\" onmouseout=\"window.status='';return true;\" title='"+bdinfo+"'>"+cname+"</a>";return (temp);}
function showun(un){temp="<a href='#' onclick=\"javascript:window.open('showuser.asp?un="+un+"','','left=100,top=50,width='+screen.availwidth*2/3+',height='+screen.availheight*3/4+',Status=yes,Resizable=no,scrollbars=yes');\" onmouseover=\"window.status='显示"+un+"的个人资料';return true;\" onmouseout=\"window.status='';return true;\" title=\"显示"+un+"的个人资料\" >"+un+"<\a> ";return(temp);}
function showhomepage(hp,pn){temp="<a href=\""+hp+"\" onmouseover=\"window.status='"+pn+"';return true;\" onmouseout=\"window.status='';return true;\" title='"+pn+"'>"+pn+"</a>";return(temp);}
function showsex(sex){	if (sex=true){temp="男";}else{temp="女";}return(temp);}
function showuserpage(pg){if(pg=="http://" | pg==""){temp="个人主页";}else{temp="<a href=\""+pg+"\">"+pg+"</a>";}return(temp);}
function showuseremail(email){temp="<a href=\"mailto:"+email+"\">"+email+"</a>";return(temp);}
function autosearch(bd,un){ temp="<a href=\"search.asp?bid="+bd+"&searchstr="+un+"\" onmouseover=\"window.status='搜索所有与"+un+"相关的贴子';return true;\" onmouseout=\"window.status='';return true;\" title=\"搜索所有与"+un+"相关的贴子\"><img border=0 src=\"..\/images\/search.gif\"></a> ";return(temp);}
function autopro(un){temp="<a href='#' onclick=\"javascript:window.open('showuser.asp?un="+un+"','','left=100,top=50,width='+screen.availwidth*2/3+',height='+screen.availheight*3/4+',Status=yes,Resizable=no,scrollbars=yes');\" onmouseover=\"window.status='显示"+un+"的个人资料';return true;\" onmouseout=\"window.status='';return true;\" title=\"显示"+un+"的个人资料\" ><img border=0 src=\"..\/images\/pro.gif\"><\a> ";return(temp);}
function autouserpage(pg,un){if(pg=="http://" | pg==""){temp="<img border=0 src=\"..\/images\/home.gif\"> ";}else{temp="<a href=\""+pg+"\" target=\"_blank\" onmouseover=\"window.status='访问"+un+"的个人主页';return true;\" onmouseout=\"window.status='';return true;\" title=\"访问"+un+"的个人主页\"><img border=0 src=\"..\/images\/home.gif\"></a> ";}return(temp);}
function autouseremail(em,un){temp="<a href=\"mailto:"+em+"\" onmouseover=\"window.status='给"+un+"写信';return true;\" onmouseout=\"window.status='';return true;\" title=\"给"+un+"写信\"><img border=0 src=\"..\/images\/email.gif\"></a> ";return(temp);}
function autoip(ip,un){temp="<img border=0 src=\"..\/images\/ip.gif\" onmouseover=\"window.status='"+un+"的IP地址是"+ip+"';return true;\" onmouseout=\"window.status='';return true;\" title=\""+un+"的ip地址是"+ip+"\"> ";return(temp);}
function autoemail(em,un){temp="<a href=\"mailto:"+em+"\" onmouseover=\"window.status='给"+un+"写信';return true;\" onmouseout=\"window.status='';return true;\" title=\"给"+un+"写信\">"+un+"</a> ";return(temp);}
function autopage(pg,un){if(pg=="http://" | pg==""){temp="";}else{temp="<a href=\""+pg+"\" target=\"_blank\" onmouseover=\"window.status='访问"+un+"的个人主页';return true;\" onmouseout=\"window.status='';return true;\" title=\"访问"+un+"的个人主页\">"+pg+"</a> ";}return(temp);}
function autoquote(bd,fd,tt,ct){temp="<a href=\"javascript:location.replace('quote.asp?bid="+bd+"&fid="+fd+"');\" onmouseover=\"window.status='回复时引用此贴';return true;\" onmouseout=\"window.status='';return true;\" title=\"回复时引用此贴\"><img border=0 src=\"..\/images\/quote.gif\"></a> ";return(temp);}
function automodify(bd,id,un,at){if(un!=at){temp="<img border=0 src=\"..\/images\/modify.gif\" onmouseover=\"window.status='只有"+at+"有权修改该贴';return true;\" onmouseout=\"window.status='';return true;\" title=\"只有"+at+"有权修改此贴\"> ";}else{temp="<a href=\"#\" onclick=\"javascript:window.open('modify.asp?bid="+bd+"&id="+id+"','','left=100,top=50,width='+screen.availwidth*2/3+',height='+screen.availheight*3/4+',status=yes,scrollbars=no,resizable=no');\" onmouseover=\"window.status='"+at+"您有权修改此贴';return true;\" onmouseout=\"window.status='';return true;\" title=\""+at+"您有权修改此贴\"><img border=0 src=\"..\/images\/modify.gif\"></a> ";}return(temp);}
function autodel(bd,id,at,hl,un,hn){if(at==un | hl.indexOf(";"+un+";")>-1 | hn.indexOf(";"+un+";")>-1){temp="<a href=\"#\" onclick=\"javascript:window.open('delete.asp?bid="+bd+"&id="+id+"','','left=100,top=50,width='+screen.availwidth*2/3+',height='+screen.availheight*3/4+',Status=yes,scrollbars=no,resizable=no');\" onmouseover=\"window.status='并不会彻底删除，只标为已删除，除版主无人能观看';return true;\" onmouseout=\"window.status='';return true;\" title=\"并不会彻底删除，只标为已删除，除版主无人能观看\"><img border=0 src=\"..\/images\/del.gif\"></a> ";}else{temp="<img border=0 src=\"..\/images\/del.gif\" onmouseover=\"window.status='只有版主和原作者才有权删除此贴';return true;\" onmouseout=\"window.status='';return true;\" titil=\"只有版主和原作者才有权删除此贴\"> ";}return(temp);}
function autoedit(ed,un,ld){if(ed==false){temp="";}else{temp="<br>此消息曾由"+un+"最后于"+ld+"编辑过";}return(temp);}
function autopm(st){temp="<a href=\"#\" onclick=\"javascript:window.open('pm.asp?st="+st+"','','left=100,top=50,width='+screen.availwidth*2/3+',height='+screen.availheight*3/4+',status=yes,scrollbars=no,resizable=no');\" onmouseover=\"window.status='给"+st+"留言';return true;\" onmouseout=\"window.status='';return true;\" title=\"给"+st+"留言\"><img border=0 src=\"..\/images\/pm.gif\"></a> ";return(temp);}
function autolevel(lvl){var i=0;temp="";for(i=0;i<=lvl;i++){temp=temp+"<img src=\"..\/images\/star.gif\">";}return(temp);};
function autoessence(bd,id,hl,un,hn){if(hl.indexOf(";"+un+";")>-1 | hn.indexOf(";"+un+";")>-1){temp="<a href=\"essence.asp?bid="+bd+"&id="+id+"\" onmouseover=\"window.status='设为精华贴';return true;\" onmouseout=\"window.status='';return true;\" title=\"设为精华贴\"><img border=0 src=\"..\/images\/essence.gif\"></a> ";}else{temp=" ";}return(temp);}
function autoreclaim(bd,id,un,hn){if(hn.indexOf(";"+un+";")>-1){temp="<a href=\"#\" onclick=\"javascript:window.open('reclaim.asp?bid="+bd+"&id="+id+"','','left=100,top=50,width='+screen.availwidth*2/3+',height='+screen.availheight*3/4+',Status=yes,scrollbars=no,resizable=no');\" onmouseover=\"window.status='回收该贴及其回复贴';return true;\" onmouseout=\"window.status='';return true;\" title=\"回收该贴及其回复贴\"><img border=0 src=\"..\/images\/reclaim.gif\"></a> ";}else{temp="<img border=0 src=\"..\/images\/reclaim.gif\" onmouseover=\"window.status='只有站长才有权此贴';return true;\" onmouseout=\"window.status='';return true;\" titil=\"只有站长才有权回收回收\"> ";}return(temp);}
function autodelete(bd,id,un,hn){if(hn.indexOf(";"+un+";")>-1){temp="<a href=\"#\" onclick=\"javascript:window.open('erase.asp?bid="+bd+"&id="+id+"','','left=100,top=50,width='+screen.availwidth*2/3+',height='+screen.availheight*3/4+',Status=yes,scrollbars=no,resizable=no');\" onmouseover=\"window.status='彻底删除此贴及其回复贴';return true;\" onmouseout=\"window.status='';return true;\" title=\"彻底删除此贴及其回复贴\"><img border=0 src=\"..\/images\/del.gif\"></a> ";}else{temp="<img border=0 src=\"..\/images\/del.gif\" onmouseover=\"window.status='只有站长才有权删除此贴';return true;\" onmouseout=\"window.status='';return true;\" titil=\"只有站长才有权删除此贴\"> ";}return(temp);}
</Script>