<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- saved from url=(0019)http://www.7758530.com-->
<HTML><HEAD><TITLE>快乐江湖总站汇款一览表</TITLE>
<META http-equiv=Content-Type content="text/html; charset=gb2312"><LINK 
href="hy/1.css" type=text/css rel=stylesheet>
<META content="MSHTML 6.00.2600.0" name=GENERATOR></HEAD>
<BODY>
<TABLE cellSpacing=0 cellPadding=0 width=450 align=center border=0>
  <TBODY>
  <TR>
    <TD bgColor=#336699>
      <TABLE cellSpacing=1 cellPadding=2 width="100%" align=center border=0>
        <TBODY>
        <TR vAlign=center align=left>
          <TD colSpan=3>
            <DIV align=left><FONT color=#ffffff><B><U>工 商 银 
            行</U></B>　异地实时到帐</FONT></DIV></TD></TR>
        <TR vAlign=center align=left>
          <TD bgColor=#ffffff>开户银行：</TD>
          <TD bgColor=#ffffff>工商银行十堰分行</TD>
          <TD bgColor=#ffffff rowSpan=3>
            <P align=center><IMG src="hy/gh_LOGO.gif" 
            border=0><FONT size=3>工商银行</FONT></P></TD></TR>
        <TR vAlign=center align=left>
          <TD bgColor=#ffffff>帐　　号：</TD>
          <TD bgColor=#ffffff>9558 8018 1010 1058700 </TD></TR>
        <TR vAlign=center align=left>
          <TD bgColor=#ffffff>开 户 名：</TD>
          <TD bgColor=#ffffff>叶进</TD></TR>
        <TR vAlign=center align=left>
          <TD bgColor=#ffffff colSpan=3>&nbsp;</TD></TR>
        <TR vAlign=center align=left>
          <TD colSpan=3>
            <DIV align=left><FONT color=#ffffff><U><B>建 设 银 
            行</B></U>　异地2-8小时到帐</FONT></DIV></TD></TR>
        <TR vAlign=center align=left>
          <TD bgColor=#ffffff>开户银行：</TD>
          <TD bgColor=#ffffff>建设银行十堰分行</TD>
          <TD bgColor=#ffffff rowSpan=3>
            <P align=center><IMG src="hy/jh_LOGO.gif" 
            border=0><FONT size=3>建设银行</FONT></P></TD></TR>
        <TR vAlign=center align=left>
          <TD bgColor=#ffffff>帐　　号：</TD>
          <TD bgColor=#ffffff>4367 4226 5042 0045 107</TD></TR>
        <TR vAlign=center align=left>
          <TD bgColor=#ffffff>开 户 名：</TD>
          <TD bgColor=#ffffff>叶进</TD></TR>
        <TR vAlign=center align=left>
          <TD bgColor=#ffffff colSpan=3>&nbsp;</TD></TR>
        <TR vAlign=center align=left>
          <TD colSpan=3>
            <DIV align=left><FONT color=#ffffff><B><U>农 业 银 
            行</U></B>　异地非双休日次日到帐</FONT></DIV></TD></TR>
        <TR vAlign=center align=left>
          <TD width=76 bgColor=#ffffff>开户银行：</TD>
          <TD width=251 bgColor=#ffffff>农业银行十堰分行</TD>
          <TD width=107 bgColor=#ffffff rowSpan=3>
            <P align=center><IMG src="hy/nh_LOGO.gif" 
            border=0><FONT size=3>农业银行</FONT></P></TD></TR>
        <TR vAlign=center align=left>
          <TD width=76 bgColor=#ffffff>金 穗 卡：</TD>
          <TD width=251 bgColor=#ffffff>95599 8074 95242 31711 </TD></TR>
        <TR vAlign=center align=left>
          <TD width=76 bgColor=#ffffff>开 户 名：</TD>
          <TD width=251 bgColor=#ffffff>叶进</TD></TR>
        <TR vAlign=center align=left>
          <TD bgColor=#ffffff colSpan=3>&nbsp;</TD></TR>
        <TR vAlign=center align=left>
          <TD colSpan=3><FONT color=#ffffff><U><B>中 国 邮 
            政</B></U>　邮政储蓄</FONT></TD></TR>
        <TR vAlign=center align=left>
          <TD bgColor=#ffffff>开户银行：</TD>
          <TD bgColor=#ffffff>湖北十堰邮政储蓄</TD>
          <TD bgColor=#ffffff rowSpan=3>
            <DIV align=center><IMG height=32 
            src="hy/postlogo.gif" width=32 border=0><FONT 
            size=3>中国邮政</FONT></DIV></TD></TR>
        <TR vAlign=center align=left>
          <TD bgColor=#ffffff>帐号：</TD>
          <TD bgColor=#ffffff>605 396005 2000 20021</TD></TR>
        <TR vAlign=center align=left>
          <TD bgColor=#ffffff>开户名：</TD>
          <TD bgColor=#ffffff>叶进</TD></TR>
        <TR vAlign=center align=left>
          <TD bgColor=#ffffff 
  colSpan=3>&nbsp;</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<P align=center>Tel:(0)13635716119,QQ:865240608<BR>
  <BR><IMG height=48 
src="hy/biaoshi.gif" width=40> </P></BODY></HTML>
