<html>
<head>
<link rel="stylesheet" href="css.css">
<title></title>
</head>
<body  background="bg1.gif" style="CURSOR: url('../images/banana.ani')" oncontextmenu='self.event.returnValue=false'>
<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td><img border="0" src="image/346.gif"></td>
      <td>
<p align="center">　</p>
<p align="center">踏入江湖的战国时期，就要充分感受战争的刺激</p>
<p align="center">这是一个弱肉强食的年代，没有强大的力量是不</p>
<p align="center">能生存的。江湖中每位大侠都应该投奔一个国家</p>
<p align="center">只要审时度势，好好观察，那么你一定可以找到</p>
<p align="center">一个安身之所，成就一代霸业。你可能会成为秦</p>
<p align="center">始王，统一六国，成为第一个始皇帝。或者你会</p>
<p align="center">成为其他国家的君主，打败强秦，创造新世纪。</p>
<p align="center">所有的一切都会在江湖中展开，这里就是你发挥</p>
<p align="center">才智的地方。成也英雄，败也英雄，各位走好。</p>
        <p>　</td>
    </tr>
  </table>
  </center>
</div>
<p align="center">　</p>
<p align="center">　</p>
<p align="center">　</p>
</body>
</html>
