
<head>
<style type='text/css'>
body{font-size:9pt;}
td{font-size:9pt;}
input{font-size:9pt;}
a{font-size:9pt; color:black;text-decoration:none;}
a:hover{color:red;text-decoration:none;}
</style>
<script language=javascript>
<!--
function exitchat(){
if(confirm('你确信退出吗？')){
parent.resfrm.location.href='exitchat.asp';
}
}

function MM_openBrWindow(theURL,winName,features) { //v2.0
window.open(theURL,winName,features);
}
//-->
</script>
<script language=javascript>
<!--
function panbang(){
	if(confirm('你确定要判帮吗？')){
	parent.resfrm.location.href='leftcorp.asp';
	}
}

function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<title></title>
<base target="_self">
</head>
<body oncontextmenu=self.event.returnValue=false  background="bg1.gif" style="CURSOR: url('../image/banana.ani')">
<div align=center>
  <table width='100%' border=1 bordercolorlight=000000 cellspacing=0 cellpadding=1 bordercolordark=FFFFFF height="433" >
    <tbody>
      <tr> 
        <td align="center" valign="middle" height="12"><a href="corp.asp" target="resfrm" onmouseover="window.status='加入门派';return true;" onmouseout="window.status='';return true;" title='加入你想去的门派'>加入门派</a></td>
      </tr>
      <tr> 
        <td align="center" valign="middle" height="12">
        <a href="../t/xw/gj.asp" target="resfrm" onmouseover="window.status='随师傅习武';return true;" onmouseout="window.status='';return true;" title="随师傅习武" style="color: #000000; cursor: e-resize; font-family: 宋体; font-size: 9pt; text-decoration: none">
        随师习武</a></td>
      </tr>
      <tr> 
        <td align="center" height="12">
        <a href="tb.asp" target="resfrm" onmouseover="window.status='加入国家';return true;" onmouseout="window.status='';return true;" title='加入你想去的国家'>投奔国家</a></td>
      </tr>
      <tr> 
        <td align="center" valign="middle" height="12">
        <a href="#" onclick="javascript:window.open('../gr/Regmodi.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='修改你的基本资料';return true;" onmouseout="window.status='';return true;" title="修改你的基本资料">
        个人修改</a></td>
      </tr>
      <tr> 
        <td align="center" height="12" >
        <a href="#" onclick="javascript:window.open('../gr/getzh.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='忘记帐号时来查找';return true;" onmouseout="window.status='';return true;" title="忘记帐号时来查找">
        查找帐号</a></td>
      </tr>
      <tr> 
        <td align="center" height="12">
        <a href="#" onclick="javascript:window.open('../gr/laren.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='拉人领奖';return true;" onmouseout="window.status='';return true;" title="拉人领奖">
        拉人领奖</a></td>
      </tr>
      <tr> 
        <td align="center" height="12">
        <a href="#" onclick="javascript:window.open('guo.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='国家列表';return true;" onmouseout="window.status='';return true;" title="国家列表">
        国家列表</a></td>
      </tr>
      <tr> 
        <td align="center" height="12">
        <a href="#" onclick="javascript:window.open('../mp/menpai.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='门派列表';return true;" onmouseout="window.status='';return true;" title="门派列表">
        门派列表</a></td>
      </tr>
      <tr> 
        <td align="center" height="12">
        <a href="#" onclick="javascript:window.open('../mp/Modatt.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='各门各派武功尽览于此';return true;" onmouseout="window.status='';return true;" title="各门各派武功尽览于此">
        武功列表</a></td>
      </tr>
      <tr> 
        <td align="center" height="12">
        <a href="#" onclick="javascript:window.open('../hy/huiy1.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='修改会员才能拥有的超酷头像';return true;" onmouseout="window.status='';return true;" title="修改会员才能拥有的超酷头像">
        会员头像</a></td>
      </tr>
      <tr> 
        <td align="center" height="13"><a href="MONEY.ASP" target="resfrm">会员领钱</a></td>
      </tr>
      <tr> 
        <td align="center" height="12">
        <a href="#" onclick="javascript:window.open('../hysq/SHOWFELL.ASP','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='达到条件申请即可成为会员';return true;" onmouseout="window.status='';return true;" title="达到条件申请即可成为会员">
        会员申请</a></td>
      </tr>
      <tr> 
        <td align="center" height="12">
        <a href="#" onclick="javascript:window.open('../gf/ma.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='看看最近江湖的人都是怎么死的';return true;" onmouseout="window.status='';return true;" title="看看最近江湖的人都是怎么死的">
        江湖命案</a></td>
      </tr>
      <tr> 
        <td align="center" height="12"><a href="webicq.asp" target="resfrm" onmouseover="window.status='允许呼叫所有在线的朋友';return true;" onmouseout="window.status='';return true;" title='允许呼叫所有在线的朋友'>在线呼叫</a></td>
      </tr>
      <tr> 
        <td align="center" height="12">
        <a href="#" onclick="javascript:window.open('../yw/topall.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='纵观天下，惟我独尊';return true;" onmouseout="window.status='';return true;" title="纵观天下，惟我独尊">
        江湖排行</a></td>
      </tr>
      <tr> 
        <td align="center" height="12">
        <a href="#" onclick="javascript:window.open('../gf/tongji.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='看看都谁变成了通缉犯';return true;" onmouseout="window.status='';return true;" title="看看都谁变成了通缉犯">
        江湖通缉</a></td>
      </tr>
      <tr> 
        <td align="center" height="12">
        <a href="#" onclick="javascript:window.open('../t/hs/fh.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='鬼魂来此修炼成人';return true;" onmouseout="window.status='';return true;" title="鬼魂来此修炼成人">
        凤凰蘖盘</a></td>
      </tr>
      <tr> 
        <td align="center" height="12">
        <a href="#" onclick="javascript:window.open('../mp/diyu.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='通缉犯来此赎罪';return true;" onmouseout="window.status='';return true;" title="通缉犯来此赎罪">
        地狱炼火</a></td>
      </tr>
          <tr> 
        <td align="center" height="12">
        <a href="#" onclick="javascript:window.open('../gf/m.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no');" onmouseover="window.status='做好事一定有好的回报';return true;" onmouseout="window.status='';return true;" title="做好事一定有好的回报">
        江湖募捐</a></td>
      </tr>
      <tr> 
        <td align="center" height="12">
        <a target="_blank" href="http://yx8.net/forum.asp">江湖论坛</a></td>
      </tr>
  <%
if session("yx8_mhjh_usercorp")="官府" and session("yx8_mhjh_usergrade")>=120 then
%>
      <tr> 
        <td align="center" height="12"><a href="#" onclick=javascript:window.open('../gf/onlinelist.asp','manage','Left=100,Top=100,Width='+screen.availwidth*2/3+',Height='+screen.availHeight*3/4+',status=no,scrollbars=no,resize=no'); onmouseover="window.status='在线聊务管理';return true;" onmouseout="window.status='';return true;" title='在线聊务管理'>官府管理</a></td>
      </tr>
       <%end if
if session("yx8_mhjh_usercorp")="官府" and session("yx8_mhjh_username")=Application("yx8_mhjh_admin") then
%>
      <tr> 
        <td align="center" height="12"><a href=yskg.asp target="resfrm">站长隐现</a></td>
      </tr>
      <tr> 
        <td align="center" valign="middle" height="12"><a href="kaiguang.asp" target="resfrm">开/关</a></td>
      </tr>
      <tr> 
        <td align="center" height="12"><a href="fafang1.ASP" target="resfrm">站长发放</a></td>
      </tr>
      <%end if%>
      <tr> 
        <td align="center" valign="middle" height="12"><a href="#" onclick='javascript:exitchat();' onmouseover="window.status='退出聊天室';return true;" onmouseout="window.status='';return true;" title='退出聊天室'>退出江湖</a></td>
      </tr>
    </tbody>
  </table>
</div>
<p>　</p>
</body>