<%@ LANGUAGE=VBScript codepage ="936" %><html>
<head>
<title>免费会员自助申请系统</title>
<LINK href="css.css" rel=stylesheet>
<style fprolloverstyle>A:hover {color: #FF0000; font-size: 14pt; font-weight: bold}
</style>
</head>
<body bgcolor="#8EB4D9" background="BG10.JPG">
<table width="643" border="1" cellpadding="5" cellspacing="5" background="b2.gif" height="383">
  <tr bgcolor="#FFFFFF">
    <td width="617" background="BG5.JPG" height="365"> 
      <p align=center><font color="#FF6600"><b><strong><blink>快乐江湖免费会员申请系统</blink></strong></b></font></p>
      <div> 
        <p>当你的等级达到快乐江湖规定的等级时,可以在线申请到快乐江湖免费会员一到三级一个月！具体說明如下:</p>
        <p>1.当 <span style="background-color: #00FF00">50&lt;你的等级&lt;55</span>-----获得自助申请免费<font color="#FF00FF"><b>一级会员一个月</b></font>的资格。。如符合条件,<a href="reg1.asp"><font color="#0000FF"><u>请点<b>这里</b>进行<b>申请</b></u></font></a></p> 
        <p>2.当 <span style="background-color: #FF00FF">250&lt;你的等级&lt;260</span>-----获得自助申请免费<font color="#FF00FF"><b>二级会员2个月</b></font>的资格。。如符合条件,<a href="reg2.asp"><font color="#0000FF"><u>请点<b>这里</b>进行<b>申</b><b>请</b></u></font></a></p> 
        <p>3.当 <span style="background-color: #FF00FF"><font color="#CCFFFF">500&lt;你的等级&lt;501</font></span>-----获得自助申请免费<font color="#FF00FF"><b>三级会员3个月</b></font>的资格。。如符合条件,<a href="reg3.asp"><font color="#0000FF"><u>请点<b>这里</b>进行<b>申</b><b>请</b></u></font></a></p> 
        
<p><B>4.当 <span style="background-color: #FF88FF"><font color="#CCFFFF">你的等级>50</font></span>-----可以用六百会费换一个月的免费会员<font color="#FF00FF"><b>一级会员/月=600会费</b></font>考虑清楚哦，申请过后会费将从你号里面直接扣除……,<a href="reg4.asp"><font color="#0000FF"><u>我<b>考虑好了</b></u></font></a></p></b>







<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b><font size="3"> 
       《 附本江湖拉人奖励表》    <img border="0" src="LIUMANG.GIF">努力。。加油。。</font></b><br> 
        </p>
        <table border="1" width="100%" height="137">
          <tr>
            <td width="25%" height="16">
              <p align="center"><b><font color="#0000FF"><img border="0" src="new.gif">拉人数</font></b></td>
            <td width="25%" height="16">
              <p align="center"><b><font color="#0000FF">奖励</font></b></td>
            <td width="25%" height="16">
              <p align="center"><b><font color="#0000FF">金卡</font></b></td>
            <td width="25%" height="16">
              <p align="center"><b><font color="#0000FF">金币</font></b></td>
          </tr>
          <tr>
            <td width="25%" height="14">
              <p align="left">30人以上</td>
            <td width="25%" height="14">
              <p align="center">门派一个，一级会员半年</td>
            <td width="25%" height="14">
              <p align="center">100</td>
            <td width="25%" height="14">
              <p align="center">100</td>
          </tr>
          <tr>
            <td width="25%" height="40">50人以上</td>
            <td width="25%" height="40">赠送六十人在线江湖管理站长或免费一级会员终身</td>
            <td width="25%" height="40">
              <p align="center">200</td>
            <td width="25%" height="40">
              <p align="center">200</td>
          </tr>
          <tr>
            <td width="25%" height="43">100人以上</td>
            <td width="25%" height="43">赠送不限在线人数管理站长或免费二级会员终身</td>
            <td width="25%" height="43">
              <p align="center">300</td>
            <td width="25%" height="43">
              <p align="center"><b><u>500</u></b></td>
          </tr>
        </table>
        <p><u><font color="#FF0000"><b>以上拉人数均需以拉人排行实际显示数为准，玩家奖励可累加，比如你先拉到三十人就可获得半年会员，会费，金币，当你拉人数累计到50人可同时再获得50人所提及的奖励</b></font></u><br>
          <br>
        <font size="3"><b>加入会员是对我們江湖建设最大的支持，更能享受更高贵的服务及更多的功能<br>
          <br>
          具体说明请</b><a href="../../chat/hy.asp" target="_blank"><font color="#0000FF"><b>点击这里!</b></font></a></font></p>
        <p align="center">　<br>
          <br>
          <%=Application("aqjh_name")%>  <font color="#0000FF"><a href="http://WWW.7758530.com"><b>快乐江湖总站首创</b></a> Copyright  
        2004-2008</font></p>
      </div>
      </td>
</tr>
</table>
<p align=center>&nbsp;</p>