<html>
<head>
<title>创派♀wWw.happyjh.com♀</title>
<link rel="stylesheet" href="../dg/Setup.css">
<meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head>
<BODY background="../JHIMG/BK_HC3W01.GIF" text=#ffffff leftmargin="0" topmargin="0" oncontextmenu=self.event.returnValue=false>
<table width="365" border="1" cellspacing="0" cellpadding="3" align="center" bordercolorlight="yellow" bordercolordark="#FFFFFF" height="138">
  <tr align="center"> 
    <td bgcolor="#000080"><img border="0" src="22.GIF"></td>
  </tr>
  <tr align="center"> 
    <td height="67" bgcolor="#000080">  要自立门户首先要满足以下条件：<p><font color="#FF00FF">体力</font>超过<b>10000</b></p>
      <p><font color="#FF00FF">内力</font>超过<b>10000</b></p>
      <p><font color="#FF00FF">武功</font>超过<b>5000</b></p>
      <p><font color="#FF00FF">攻击</font>超过<b>500</b></p>
      <p><font color="#FF00FF">防御</font>超过<b>1000</b></p>
      <p><font color="#FF00FF">魅力</font>超过<b>10000</b></p>
      <p><font color="#FF00FF">道德</font>超过<b>10000</b></p>
      <p><font color="#FF00FF">银两</font>超过<b>1亿</b></p>
      <p><font color="#FF00FF">战斗等级</font>超过<b>50级</b></p>
      <p><font color="#FF00FF">拉人数</font>超过<b>10人<br>注：所拉来的人的战斗等级在20级以上才算数</b></p>
      <p>创建门派时收取<b><font color="#00FF00">5千万两</font></b>红包，另取<b><font color="#00FF00">5千万两</font></b>来做为门派基金。</p>
    </td>
  </tr>
  <tr align="center"> 
    <td bgcolor="#000080">本江湖允许自建15个门派，30天后少于10人的门派自动删除，符合以上条件的用户请<a href="cpsq.asp"><b><font color="#00FFFF">进来</font></b></a>......</td>
  </tr>
</table>
</body>
</html>


