
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>英雄排行榜</title><LINK href="../chatroom/css.css" rel=stylesheet>
</head>
<body background='../chatroom/bg1.gif' oncontextmenu=self.event.returnValue=false>

<div align="center">
<center>
<table border="1" width="100%" cellspacing="0" cellpadding="0" bordercolorlight="#000000" bordercolordark="#FFFFFF">
<tr>
<td width="20%" align="center"><a href="TOP.ASP" target="main">全体排行</a></td>
<td width="20%" align="center"><a href="TOP1.ASP" target="main">掌门排行</a></td>
<td width="20%" align="center"><a href="TOP2.ASP" target="main">大侠排行</a></td>
<td width="20%" align="center"><a href="TOP3.ASP" target="main">女侠排行</a></td>
<td width="20%" align="center"><a href="top4.asp" target="main">官府排行</a></td>
</tr>
</table>
</center>
</div>

</body>

</html>
