<html>

<head>
<meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=gb2312">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>英雄排行榜</title>
</head>

<frameset framespacing="0" border="0" rows="373,*" frameborder="0">
<frame name="main" scrolling="auto" target="main" src="TOP.ASP">
<frame name="loot" src="down.asp" scrolling="auto">
<noframes>
<body>

<p>此网页使用了框架，但您的浏览器不支持框架。</p>

</body>
</noframes>
</frameset>

</html>
