<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<title>-会员修炼金币、金卡-</title>
<link href="play.css" tppabs="play.css" rel="stylesheet">
</head>

<body topmargin="5" bgcolor="#FFFFFF" leftmargin="5" background="../chat/back.jpg">
<table border="0" cellspacing="0" cellpadding="0" width="778">
<tr>
<td>
  <p align="center"><b><font size="3" color="#990000">会员修炼金币、金卡</font></b></p>
      <p align="center"><a href="../taiqiu/zh.asp"><b><img border="0" src="../chat/img/room1.gif" width="18" height="18"> 
        <font color="#009900">转换市场</font></b></a><b><font color="#FF0000">&nbsp;</font> 
        &nbsp; <a href="../hyxuewu"><font color="#FF0000"><img border="0" src="../chat/pic/dz25.gif" width="50" height="61"><font color="#009933">会员武馆</font></font></a></b></p>    
</td>   
</tr>   
</table>   
现有会员修炼： <font color="#FF0000">（修练金币、会员金卡都要损失一些看见或看不见的东西，请各位侠士慎重选择）</font><br>         
<TABLE align=left border=1 borderColor=#cccccc borderColorDark=#ffffff         
borderColorLight=#000000 cellPadding=0 cellSpacing=0         
style="FONT-SIZE: 9pt" width="100%" bordercolordard="#ffffff">         
<TBODY>         
<TR>         
<TD width="22%">         
<DIV align=center>物品</DIV>        
</TD>        
<TD width="18%">        
<DIV align=center>需要指数</DIV>        
</TD>        
<TD width="20%">        
<DIV align=center>增加数量</DIV>        
</TD>        
<TD width="20%">        
<div align="center">其它指数</div>        
</TD>        
<TD width="20%">        
<DIV align=center>是否修练</DIV>        
</TD>        
</TR>        
<TR>        
<TD width="22%">        
<DIV align=center><img border="0" src="../chat/img/menoy.gif" width="50" height="40"> 
  金币 </DIV>       
<DIV align=center></DIV>       
<DIV align=center></DIV>       
</TD>       
<TD width="18%">       
<DIV align=center>体力－10000点<br>       
内力－10000</DIV>      
<DIV align=center>银两-200万</DIV>     
</TD>     
<TD width="20%">     
<DIV align=center>金币＋1</DIV>     
<DIV align=center></DIV>     
<DIV align=center></DIV>     
<DIV align=center></DIV>     
<DIV align=center></DIV>     
<DIV align=center></DIV>     
<DIV align=center></DIV>     
</TD>     
<TD width="20%">     
<div align="center">经验＋0<br>     
防御＋0</div>     
</TD>     
<TD width="20%">     
<DIV align=center><A     
href="dg1.asp"><img border="0" src="../chat/img/pic15.gif" width="60" height="73">修练</A> </DIV>     
</TD>     
<tr>   
<TD width="22%">        
<DIV align=center><img border="0" src="../chat/img/menoy.gif" width="50" height="40"> 
  金币 </DIV>       
<DIV align=center></DIV>       
<DIV align=center></DIV>       
</TD>       
<TD width="18%">       
<DIV align=center>法力－1500点<br>
          轻功－1500</DIV>    
</TD>   
<TD width="20%">   
<DIV align=center>金币＋1</DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
</TD>   
<TD width="20%">   
<div align="center">经验＋0<br>   
防御＋0</div>   
</TD>   
<TD width="20%">   
<DIV align=center><A   
href="dg3.asp"><img border="0" src="../chat/img/pic15.gif" width="60" height="73">修练</A> </DIV>   
</TD>   
</tr> 
<tr> 
<TD width="22%">   
<DIV align=center><IMG src="jk.gif"> 会员金卡 </DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
</TD>   
<TD width="18%">   
<DIV align=center>体力－200000点</DIV>   
<DIV align=center>内力－200000</DIV>   
        <DIV align=center>银两-3000万</DIV>   
</TD>   
<TD width="20%">   
<DIV align=center>会员金卡＋1</DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
</TD>   
<TD width="20%">   
<div align="center">经验＋0<br>   
防御＋0</div>   
</TD>   
<TD width="20%">   
<DIV align=center><A   
href="dg2.asp"><img border="0" src="../chat/pic/dz23.gif" width="50" height="58">修练</A> </DIV>   
</TD>   
</tr> 
<TR>   
<TD width="22%">   
<DIV align=center><IMG src="jk.gif"> 会员金卡 </DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
</TD>   
<TD width="18%">   
<DIV align=center>法力－15000点<br>
          轻功－15000</DIV>   
</TD>   
<TD width="20%">   
<DIV align=center>会员金卡＋1</DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
<DIV align=center></DIV>   
</TD>   
<TD width="20%">   
<div align="center">经验＋0<br>   
防御＋0</div>   
</TD>   
<TD width="20%">   
<DIV align=center><A   
href="dg4.asp"><img border="0" src="../chat/pic/dz23.gif" width="50" height="58">修练</A> </DIV>   
</TD>   
</TBODY>
</TABLE>   

</BODY>  
</HTML>