<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<link href="../../style.css" rel=stylesheet type="text/css">
<title>挖掘宝藏</title></HEAD>
<body oncontextmenu=self.event.returnValue=false bgcolor="#000000" text="#ffffff">
<%session("wabao")=true%>
<p align="center">　</p>
<p align="center"><font color="#FFFF00"><img border="0" src="../../Image/251.GIF"></font><img border="0" src="../../Image/251.GIF"><font color="#FFFF00">&nbsp;</font><img border="0" src="../../Image/251.GIF"><font color="#FFFF00"><img border="0" src="../../Image/251.GIF"><img border="0" src="../../Image/252.gif"></font><img border="0" src="../../Image/252.gif"><img border="0" src="../../Image/252.gif"><img border="0" src="../../Image/252.gif"></p>
<p align="center">　</p>
<p align="center"><a href="#" onclick="javascript:tiewin=window.open('diao.asp','diao','scrollbars=no,resizable=yes,width=700,height=420');" onmouseover="window.status='';return true;" onmouseout="window.status='';return true;" title><font color="#FFFF00" size="2">开始挖宝藏</font></a></p>
<p align="center"><font color="#FFFFFF" size="2">每挖一次宝藏都会用去50至120不等的体力，挖到后不拿走的<br>话,被抢走的机会是10%，只要看到你的手上抱有黄金就点击下<br>去.不过,体力1000以下的大侠是不能探宝的挖宝藏一定要注意<br>时机,因为这一带挖的人很多,一不小心就会被抢走,有时候遇到<br>强盗还会......</font></p>

<p align="center">　</p>
<p align="center">　</p>
<p align="center"></p>

</BODY>
</HTML>