<html>
<head>
<body leftmargin="0" topmargin="0" bgcolor="#CCCCCC" background="../chat/f2.gif">
<title><%=Application("aqjh_chatroomname")%>会员充值系统</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312"></head>
<SCRIPT>document.write(unescape("%3Cscript%3Edocument.oncontextmenu%3Dnew%20Function%28%22event.returnValue%3Dfalse%22%29%0D%0Adocument.onselectstart%3Dnew%20Function%28%22event.returnValue%3Dfalse%22%29%3C/script%3E"))</SCRIPT>
<body bgcolor="#000000" oncontextmenu="return false;" onselectstart="return false">
<table width="692" border="3" align="center" cellpadding="8" cellspacing="8" bordercolor="#6666CC">
  <!--DWLayoutTable-->
  <tr> 
    <td height="36" colspan="6" align="center" valign="top"><%=Application("aqjh_chatroomname")%>会员充值卡 
      <script language="JavaScript">
function load()
{var name=navigator.appName
var vers=navigator.appVersion
if(name=="Netscape")
{window.location.reload()
}else
{history.go(0)
}}
</script> <a href="javascript:load()">【刷新】</a> <a href="javascript:history.go(-1)">【返回】</a> 
    </td>
  </tr>
  <tr> 
    <td height="30" colspan="6" align="center" valign="top">充值卡的用途:</td>
  </tr>
  <tr> 
    <td width="20%"  align="center">1张充值卡=5000存点<br> <a href="czk1.asp">点击充值存点</a></td>
    <td width="20%" align="center">1张充值卡=5元金卡<br> <a href="czk2.asp">点击充值金卡</a></td>
    <td width="20%" align="center">1张充值卡=50个金币<br> <a href="czk3.asp">点击充值金币</a></td>
    <td width="20%" align="center">1张充值卡=5000个银币<br> <a href="czk4.asp">点击充值银币</a></td>
    <td width="20%" align="center">充值卡可以充值会员日期和会员等级。<br> <a href="zhuan.asp">点击充值会员</a></td>
  </tr>
  <tr> 
    <td height="34" colspan="6" align="center" valign="top">充值卡的价格：</td>
  </tr>
  <tr> 
    <td height="52" colspan="6" align="center" valign="top"><img src="y_2.jpg"> 
      <img src="y_3.jpg"> <img src="y_4.jpg"> <img src="y_7.jpg"> <br>
        50元人民币=30张充值卡（一次最少购买50元</td>
  </tr>
  <tr> 
    <td height="30" colspan="6" align="center" valign="top">存点卡的价格：</td>
  </tr>
  <tr> 
    <td width="20%" height="88" align="center" valign="top" ><img src="f024.jpg" width="118"><br>
      20元/张 加存点20000。</td>
    <td width="20%" align="center" valign="top" ><img src="f028.jpg" width="118"><br>
      40元/张 加存点40000。</td>
    <td width="20%" align="center" valign="top" ><img src="f032.jpg" width="118"><br>
      60元/张 加存点60000。</td>
    <td width="20%" align="center" valign="top"><img src="f037.jpg" width="118"><br>
      80元/张 加存点80000。</td>
    <td width="20%" align="center"  valign="top"><img src="f041.jpg" width="118"><br>
      100元/张 加存点100000。</td>
  </tr>
  <tr> 
    <td height="30" colspan="6" align="center" valign="top"><a href="../chat/hy.asp">汇款地址：点击进入</a></td>
  </tr>
  <tr> 
    <td height="36" colspan="6" align="center" valign="top"><%=Application("aqjh_chatroomname")%></td>
    </tr>
</table>
</body>    
</html>