<html>
<head>
<title>myhome1.jpg</title>
<meta http-equiv="Content-Type" content="text/html;">
<!-- Fireworks MX Dreamweaver MX target.  Created Tue Jul 22 23:10:15 GMT+0800 (?D1¨²¡À¨º¡Á?¨º¡À??) 2003-->
</head>
<body bgcolor="#ffffff">
<table border="0" cellpadding="0" cellspacing="0" width="675">
<!-- fwtable fwsrc="Î´ÃüÃû" fwbase="myhome1.jpg" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
  <tr>
   <td><img src="myhome/spacer.gif" width="206" height="1" border="0" alt=""></td>
   <td><img src="myhome/spacer.gif" width="220" height="1" border="0" alt=""></td>
   <td><img src="myhome/spacer.gif" width="249" height="1" border="0" alt=""></td>
   <td><img src="myhome/spacer.gif" width="1" height="1" border="0" alt=""></td>
  </tr>

  <tr>
   <td><img name="myhome1_r1_c1" src="myhome/myhome1_r1_c1.jpg" width="206" height="63" border="0" alt=""></td>
   <td><img name="myhome1_r1_c2" src="myhome/myhome1_r1_c2.jpg" width="220" height="63" border="0" alt=""></td>
   <td><img name="myhome1_r1_c3" src="myhome/myhome1_r1_c3.jpg" width="249" height="63" border="0" alt=""></td>
   <td><img src="myhome/spacer.gif" width="1" height="63" border="0" alt=""></td>
  </tr>
  <tr>
   <td><img name="myhome1_r2_c1" src="myhome/myhome1_r2_c1.jpg" width="206" height="66" border="0" alt=""></td>
   <td><img name="myhome1_r2_c2" src="myhome/myhome1_r2_c2.jpg" width="220" height="66" border="0" usemap="#m_myhome1_r2_c2" alt=""></td>
   <td><img name="myhome1_r2_c3" src="myhome/myhome1_r2_c3.jpg" width="249" height="66" border="0" usemap="#m_myhome1_r2_c3" alt=""></td>
   <td><img src="myhome/spacer.gif" width="1" height="66" border="0" alt=""></td>
  </tr>
  <tr>
   <td><img name="myhome1_r3_c1" src="myhome/myhome1_r3_c1.jpg" width="206" height="77" border="0" alt=""></td>
   <td><img name="myhome1_r3_c2" src="myhome/myhome1_r3_c2.jpg" width="220" height="77" border="0" usemap="#m_myhome1_r3_c2" alt=""></td>
   <td><img name="myhome1_r3_c3" src="myhome/myhome1_r3_c3.jpg" width="249" height="77" border="0" usemap="#m_myhome1_r3_c3" alt=""></td>
   <td><img src="myhome/spacer.gif" width="1" height="77" border="0" alt=""></td>
  </tr>
  <tr>
   <td><img name="myhome1_r4_c1" src="myhome/myhome1_r4_c1.jpg" width="206" height="64" border="0" usemap="#m_myhome1_r4_c1" alt=""></td>
   <td><img name="myhome1_r4_c2" src="myhome/myhome1_r4_c2.jpg" width="220" height="64" border="0" alt=""></td>
   <td><img name="myhome1_r4_c3" src="myhome/myhome1_r4_c3.jpg" width="249" height="64" border="0" alt=""></td>
   <td><img src="myhome/spacer.gif" width="1" height="64" border="0" alt=""></td>
  </tr>
  <tr>
   <td><img name="myhome1_r5_c1" src="myhome/myhome1_r5_c1.jpg" width="206" height="69" border="0" usemap="#m_myhome1_r5_c1" alt=""></td>
   <td><img name="myhome1_r5_c2" src="myhome/myhome1_r5_c2.jpg" width="220" height="69" border="0" usemap="#m_myhome1_r5_c2" alt=""></td>
   <td><img name="myhome1_r5_c3" src="myhome/myhome1_r5_c3.jpg" width="249" height="69" border="0" alt=""></td>
   <td><img src="myhome/spacer.gif" width="1" height="69" border="0" alt=""></td>
  </tr>
  <tr>
   <td><img name="myhome1_r6_c1" src="myhome/myhome1_r6_c1.jpg" width="206" height="101" border="0" usemap="#m_myhome1_r6_c1" alt=""></td>
   <td><img name="myhome1_r6_c2" src="myhome/myhome1_r6_c2.jpg" width="220" height="101" border="0" alt=""></td>
   <td><img name="myhome1_r6_c3" src="myhome/myhome1_r6_c3.jpg" width="249" height="101" border="0" alt=""></td>
   <td><img src="myhome/spacer.gif" width="1" height="101" border="0" alt=""></td>
  </tr>
<map name="m_myhome1_r2_c2">
<area shape="rect" coords="111,59,167,81" href="fw/xiaowu2.asp" target="_blank" alt="" >
</map>
<map name="m_myhome1_r2_c3">
<area shape="rect" coords="104,20,143,45" href="11.htm" alt="" >
</map>
<map name="m_myhome1_r3_c2">
<area shape="rect" coords="32,58,101,77" href="gr/SHEEP/feedsheep.asp" target="_blank" alt="" >
<area shape="rect" coords="111,-7,167,15" href="fw/xiaowu2.asp" target="_blank" alt="" >
</map>
<map name="m_myhome1_r3_c3">
<area shape="rect" coords="14,54,91,77" href="fw/xiaowu.asp" alt="" >
</map>
<map name="m_myhome1_r4_c1">
<area shape="rect" coords="111,53,147,71" href="fw/xiaowu1.asp?room=g" target="_blank" alt="" >
</map>
<map name="m_myhome1_r5_c1">
<area shape="rect" coords="105,51,161,72" href="fw/xiaowu3.asp" alt="" >
<area shape="rect" coords="111,-11,147,7" href="fw/xiaowu1.asp?room=g" target="_blank" alt="" >
</map>
<map name="m_myhome1_r5_c2">
<area shape="rect" coords="35,23,109,41" href="gr/dongfang/Marriage.asp" target="_blank" alt="" >
</map>
<map name="m_myhome1_r6_c1">
<area shape="rect" coords="105,-18,161,3" href="fw/xiaowu3.asp" alt="" >
</map>
</table>
</body>
</html>
